// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class CreateInput {
    /**
     * Creates a new CreateInput instance.
     * @param {Partial<CreateInput>} [$$source = {}] - The source object to create the CreateInput.
     */
    constructor($$source = {}) {
        if (!("workspace" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["workspace"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["shell"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["arguments"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["rows"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["cols"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CreateInput}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("arguments" in $$parsedSource) {
            $$parsedSource["arguments"] = $$createField2_0($$parsedSource["arguments"]);
        }
        return new CreateInput(/** @type {Partial<CreateInput>} */($$parsedSource));
    }
}

export class Session {
    /**
     * Creates a new Session instance.
     * @param {Partial<Session>} [$$source = {}] - The source object to create the Session.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("workspace" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["workspace"] = "";
        }
        if (!("shell" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["shell"] = "";
        }
        if (!("pid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pid"] = 0;
        }
        if (!("rows" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rows"] = 0;
        }
        if (!("cols" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cols"] = 0;
        }
        if (!("startedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["startedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Session instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Session}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Session(/** @type {Partial<Session>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
