// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/openmodu/oneshot/internal/app/config"
	"github.com/openmodu/oneshot/internal/data"
	"github.com/openmodu/oneshot/internal/repo/agents"
	"github.com/openmodu/oneshot/internal/repo/artifacts"
	"github.com/openmodu/oneshot/internal/repo/billing"
	"github.com/openmodu/oneshot/internal/repo/conversations"
	"github.com/openmodu/oneshot/internal/repo/orders"
	"github.com/openmodu/oneshot/internal/repo/sessions"
	"github.com/openmodu/oneshot/internal/repo/users"
	"github.com/openmodu/oneshot/internal/service"
	"github.com/openmodu/oneshot/internal/usecase"
	agents2 "github.com/openmodu/oneshot/internal/usecase/agents"
	artifacts2 "github.com/openmodu/oneshot/internal/usecase/artifacts"
	"github.com/openmodu/oneshot/internal/usecase/auth"
	billing2 "github.com/openmodu/oneshot/internal/usecase/billing"
	conversations2 "github.com/openmodu/oneshot/internal/usecase/conversations"
	"github.com/openmodu/oneshot/internal/usecase/execution"
	orders2 "github.com/openmodu/oneshot/internal/usecase/orders"
)

// Injectors from wire.go:

func initializeServices(cfg config.Config) (*service.Services, func(), error) {
	mySQLDSN := provideMySQLDSN(cfg)
	dataData, cleanup, err := data.ProvideData(mySQLDSN)
	if err != nil {
		return nil, nil, err
	}
	sql := data.ProvideSQL(dataData)
	agentsRepo := agents.NewAgentsRepo(sql)
	artifactsRepo := artifacts.NewArtifactsRepo(sql)
	billingRepo := billing.NewBillingRepo(sql)
	conversationsRepo := conversations.NewConversationsRepo(sql)
	ordersRepo := orders.NewOrdersRepo(sql)
	sessionsRepo := sessions.NewSessionsRepo(sql)
	usersRepo := users.NewUsersRepo(sql)
	oneShotRepo := data.NewOneShotRepo(agentsRepo, artifactsRepo, billingRepo, conversationsRepo, ordersRepo, sessionsRepo, usersRepo)
	repository := usecase.ProvideAuthRepository(oneShotRepo)
	sessionStore := usecase.ProvideAuthSessionStore(oneShotRepo)
	authUsecase := auth.NewUsecase(repository, sessionStore)
	agentsRepository := usecase.ProvideAgentRepository(oneShotRepo)
	agentsUsecase := agents2.NewUsecase(agentsRepository)
	artifactsRepository := usecase.ProvideArtifactRepository(oneShotRepo)
	orderRepository := usecase.ProvideArtifactOrderRepository(oneShotRepo)
	artifactsUsecase := artifacts2.NewUsecase(artifactsRepository, orderRepository)
	billingRepository := usecase.ProvideBillingRepository(oneShotRepo)
	billingUsecase := billing2.NewUsecase(billingRepository)
	conversationsRepository := usecase.ProvideConversationRepository(oneShotRepo)
	agentGetter := usecase.ProvideConversationAgentGetter(agentsUsecase)
	agentRepository := usecase.ProvideOrderAgentRepository(oneShotRepo)
	ordersRepository := usecase.ProvideOrderRepository(oneShotRepo)
	executionOrderRepository := usecase.ProvideExecutionOrderRepository(oneShotRepo)
	artifactRecorder := usecase.ProvideExecutionArtifactRecorder(artifactsUsecase)
	executionAgentResolver := usecase.ProvideExecutionAgentResolver(oneShotRepo)
	agentEngine := provideAgentEngine(cfg)
	executionConfig := provideExecutionConfig(cfg)
	executionUsecase := execution.NewUsecase(executionOrderRepository, executionAgentResolver, artifactRecorder, agentEngine, executionConfig)
	runSessionReader := usecase.ProvideOrderRunSessionReader(executionUsecase)
	ordersUsecase := orders2.NewUsecase(agentRepository, ordersRepository, billingUsecase, runSessionReader)
	orderCreator := usecase.ProvideConversationOrderCreator(ordersUsecase)
	conversationsUsecase := conversations2.NewUsecase(conversationsRepository, agentGetter, orderCreator)
	services := service.NewServices(authUsecase, agentsUsecase, artifactsUsecase, billingUsecase, conversationsUsecase, executionUsecase, ordersUsecase)
	return services, func() {
		cleanup()
	}, nil
}
