// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/openmodu/oneshot/internal/app/config"
	"github.com/openmodu/oneshot/internal/data"
	"github.com/openmodu/oneshot/internal/repo/agents"
	"github.com/openmodu/oneshot/internal/repo/billing"
	"github.com/openmodu/oneshot/internal/repo/orders"
	"github.com/openmodu/oneshot/internal/repo/users"
	"github.com/openmodu/oneshot/internal/service"
	"github.com/openmodu/oneshot/internal/usecase"
	agents2 "github.com/openmodu/oneshot/internal/usecase/agents"
	"github.com/openmodu/oneshot/internal/usecase/auth"
	billing2 "github.com/openmodu/oneshot/internal/usecase/billing"
	orders2 "github.com/openmodu/oneshot/internal/usecase/orders"
)

// Injectors from wire.go:

func initializeServices(cfg config.Config) (*service.Services, func(), error) {
	mySQLDSN := provideMySQLDSN(cfg)
	dataData, cleanup, err := data.ProvideData(mySQLDSN)
	if err != nil {
		return nil, nil, err
	}
	sql := data.ProvideSQL(dataData)
	agentsRepo := agents.NewAgentsRepo(sql)
	billingRepo := billing.NewBillingRepo(sql)
	ordersRepo := orders.NewOrdersRepo(sql)
	usersRepo := users.NewUsersRepo(sql)
	oneShotRepo := data.NewOneShotRepo(agentsRepo, billingRepo, ordersRepo, usersRepo)
	repository := usecase.ProvideAuthRepository(oneShotRepo)
	authUsecase := auth.NewUsecase(repository)
	agentsRepository := usecase.ProvideAgentRepository(oneShotRepo)
	agentsUsecase := agents2.NewUsecase(agentsRepository)
	billingRepository := usecase.ProvideBillingRepository(oneShotRepo)
	billingUsecase := billing2.NewUsecase(billingRepository)
	agentRepository := usecase.ProvideOrderAgentRepository(oneShotRepo)
	ordersRepository := usecase.ProvideOrderRepository(oneShotRepo)
	ordersUsecase := orders2.NewUsecase(agentRepository, ordersRepository, billingUsecase)
	services := service.NewServices(authUsecase, agentsUsecase, billingUsecase, ordersUsecase)
	return services, func() {
		cleanup()
	}, nil
}
