// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agentrun$0 from "../agentrun/models.js";

/**
 * Frame identifies one runtime event inside an orchestrated workflow run.
 */
export class Frame {
    /**
     * Creates a new Frame instance.
     * @param {Partial<Frame>} [$$source = {}] - The source object to create the Frame.
     */
    constructor($$source = {}) {
        if (!("runId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["runId"] = "";
        }
        if (!("stepRunId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["stepRunId"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["seq"] = undefined;
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {agentrun$0.EventKind}
             */
            this["kind"] = agentrun$0.EventKind.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * StreamID is stable for all chunks belonging to one logical message,
             * reasoning block, or tool output. Empty identifies an atomic event.
             * @member
             * @type {string | undefined}
             */
            this["streamId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Phase controls whether Text starts, appends to, replaces, or completes a
             * logical stream. Revision is assigned by the orchestration collector after
             * it batches provider token deltas.
             * @member
             * @type {agentrun$0.StreamPhase | undefined}
             */
            this["phase"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["revision"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Text is the human-meaningful payload: message prose, command, file path,
             * or error description, depending on Kind.
             * @member
             * @type {string | undefined}
             */
            this["text"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Raw is the original JSONL line from the runtime, retained for debugging
             * and forward compatibility with fields we do not yet model.
             * @member
             * @type {string | undefined}
             */
            this["raw"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Failed reports that this individual event is an error: a tool that
             * returned an error, not a run that ended badly. A step can fail while most
             * of its tool calls succeeded, so callers must not infer one from the other.
             * @member
             * @type {boolean | undefined}
             */
            this["failed"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Permission is populated for permission_request and permission_resolved
             * events. PermissionDecision is "allow" or "deny" on the resolved event.
             * @member
             * @type {agentrun$0.PermissionRequest | null | undefined}
             */
            this["permission"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["permissionDecision"] = undefined;
        }
        if (!("at" in $$source)) {
            /**
             * At is when the engine observed the event.
             * @member
             * @type {string}
             */
            this["at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Frame instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Frame}
     */
    static createFrom($$source = {}) {
        const $$createField10_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("permission" in $$parsedSource) {
            $$parsedSource["permission"] = $$createField10_0($$parsedSource["permission"]);
        }
        return new Frame(/** @type {Partial<Frame>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = agentrun$0.PermissionRequest.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
