// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    Capability,
    CloseDocumentInput,
    CloseWorkspaceInput,
    DefinitionInput,
    DetectInput,
    Location,
    Position,
    Range,
    SyncDocumentInput
} from "./models.js";
