// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ClaudeConfiguration {
    /**
     * Creates a new ClaudeConfiguration instance.
     * @param {Partial<ClaudeConfiguration>} [$$source = {}] - The source object to create the ClaudeConfiguration.
     */
    constructor($$source = {}) {
        if (!("models" in $$source)) {
            /**
             * @member
             * @type {ClaudeModelInfo[]}
             */
            this["models"] = [];
        }
        if (!("efforts" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["efforts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClaudeConfiguration instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ClaudeConfiguration}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField0_0($$parsedSource["models"]);
        }
        if ("efforts" in $$parsedSource) {
            $$parsedSource["efforts"] = $$createField1_0($$parsedSource["efforts"]);
        }
        return new ClaudeConfiguration(/** @type {Partial<ClaudeConfiguration>} */($$parsedSource));
    }
}

export class ClaudeModelInfo {
    /**
     * Creates a new ClaudeModelInfo instance.
     * @param {Partial<ClaudeModelInfo>} [$$source = {}] - The source object to create the ClaudeModelInfo.
     */
    constructor($$source = {}) {
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("displayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }
        if (!("alias" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["alias"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClaudeModelInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ClaudeModelInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClaudeModelInfo(/** @type {Partial<ClaudeModelInfo>} */($$parsedSource));
    }
}

export class CodexConfiguration {
    /**
     * Creates a new CodexConfiguration instance.
     * @param {Partial<CodexConfiguration>} [$$source = {}] - The source object to create the CodexConfiguration.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["model"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["reasoningEffort"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["serviceTier"] = undefined;
        }
        if (!("models" in $$source)) {
            /**
             * @member
             * @type {CodexModelInfo[]}
             */
            this["models"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CodexConfiguration instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CodexConfiguration}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField3_0($$parsedSource["models"]);
        }
        return new CodexConfiguration(/** @type {Partial<CodexConfiguration>} */($$parsedSource));
    }
}

export class CodexModelInfo {
    /**
     * Creates a new CodexModelInfo instance.
     * @param {Partial<CodexModelInfo>} [$$source = {}] - The source object to create the CodexModelInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("displayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (!("defaultReasoningEffort" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["defaultReasoningEffort"] = "";
        }
        if (!("reasoningEfforts" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["reasoningEfforts"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {CodexServiceTier[] | undefined}
             */
            this["serviceTiers"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["defaultServiceTier"] = undefined;
        }
        if (!("isDefault" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDefault"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CodexModelInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CodexModelInfo}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType2;
        const $$createField6_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("reasoningEfforts" in $$parsedSource) {
            $$parsedSource["reasoningEfforts"] = $$createField5_0($$parsedSource["reasoningEfforts"]);
        }
        if ("serviceTiers" in $$parsedSource) {
            $$parsedSource["serviceTiers"] = $$createField6_0($$parsedSource["serviceTiers"]);
        }
        return new CodexModelInfo(/** @type {Partial<CodexModelInfo>} */($$parsedSource));
    }
}

export class CodexServiceTier {
    /**
     * Creates a new CodexServiceTier instance.
     * @param {Partial<CodexServiceTier>} [$$source = {}] - The source object to create the CodexServiceTier.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CodexServiceTier instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CodexServiceTier}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CodexServiceTier(/** @type {Partial<CodexServiceTier>} */($$parsedSource));
    }
}

/**
 * Event is a single normalized step emitted while an agent runs. Raw preserves
 * the original JSON line so nothing is lost, while Kind/Text give callers a
 * runtime-agnostic view suitable for display and persistence.
 */
export class Event {
    /**
     * Creates a new Event instance.
     * @param {Partial<Event>} [$$source = {}] - The source object to create the Event.
     */
    constructor($$source = {}) {
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {EventKind}
             */
            this["kind"] = EventKind.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * StreamID is stable for all chunks belonging to one logical message,
             * reasoning block, or tool output. Empty identifies an atomic event.
             * @member
             * @type {string | undefined}
             */
            this["streamId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Phase controls whether Text starts, appends to, replaces, or completes a
             * logical stream. Revision is assigned by the orchestration collector after
             * it batches provider token deltas.
             * @member
             * @type {StreamPhase | undefined}
             */
            this["phase"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["revision"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Text is the human-meaningful payload: message prose, command, file path,
             * or error description, depending on Kind.
             * @member
             * @type {string | undefined}
             */
            this["text"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Raw is the original JSONL line from the runtime, retained for debugging
             * and forward compatibility with fields we do not yet model.
             * @member
             * @type {string | undefined}
             */
            this["raw"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Failed reports that this individual event is an error: a tool that
             * returned an error, not a run that ended badly. A step can fail while most
             * of its tool calls succeeded, so callers must not infer one from the other.
             * @member
             * @type {boolean | undefined}
             */
            this["failed"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Permission is populated for permission_request and permission_resolved
             * events. PermissionDecision is "allow" or "deny" on the resolved event.
             * @member
             * @type {PermissionRequest | null | undefined}
             */
            this["permission"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["permissionDecision"] = undefined;
        }
        if (!("at" in $$source)) {
            /**
             * At is when the engine observed the event.
             * @member
             * @type {string}
             */
            this["at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Event instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Event}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("permission" in $$parsedSource) {
            $$parsedSource["permission"] = $$createField7_0($$parsedSource["permission"]);
        }
        return new Event(/** @type {Partial<Event>} */($$parsedSource));
    }
}

/**
 * EventKind is the normalized category of a streamed run event. It is the
 * common denominator across every supported runtime.
 * @readonly
 * @enum {string}
 */
export const EventKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * KindStarted marks the beginning of a run (session/thread established).
     */
    KindStarted: "started",

    /**
     * KindReasoning carries the agent's private thinking, when the runtime
     * surfaces it. Useful for live progress but not part of the deliverable.
     */
    KindReasoning: "reasoning",

    /**
     * KindMessage carries assistant prose addressed to the user.
     */
    KindMessage: "message",

    /**
     * KindToolUse marks the agent invoking a tool (shell command, file edit).
     */
    KindToolUse: "tool_use",

    /**
     * KindToolResult carries the result of a prior tool invocation.
     */
    KindToolResult: "tool_result",

    /**
     * KindFileChange marks the agent creating or modifying a file.
     */
    KindFileChange: "file_change",

    /**
     * KindUsage carries token/cost accounting for the turn.
     */
    KindUsage: "usage",

    /**
     * KindResult marks the terminal outcome of the run.
     */
    KindResult: "result",

    /**
     * KindError carries a runtime or parse error encountered mid-stream.
     */
    KindError: "error",

    /**
     * KindPermissionRequest asks the host application to approve or deny a
     * tool call while the runtime remains blocked on that decision.
     */
    KindPermissionRequest: "permission_request",

    /**
     * KindPermissionResolved records the decision returned to the runtime.
     */
    KindPermissionResolved: "permission_resolved",
};

/**
 * PermissionRequest is the runtime-neutral payload shown by the desktop
 * approval card. ID identifies the blocking control request, while ToolUseID
 * identifies the eventual tool call in the provider transcript.
 */
export class PermissionRequest {
    /**
     * Creates a new PermissionRequest instance.
     * @param {Partial<PermissionRequest>} [$$source = {}] - The source object to create the PermissionRequest.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["toolUseId"] = undefined;
        }
        if (!("toolName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["toolName"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["input"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {PermissionUpdate[] | undefined}
             */
            this["suggestions"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["title"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["displayName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["decisionReason"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["suppressAlwaysAllow"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["requiresUserInteraction"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PermissionRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PermissionRequest}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType9;
        const $$createField4_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("input" in $$parsedSource) {
            $$parsedSource["input"] = $$createField3_0($$parsedSource["input"]);
        }
        if ("suggestions" in $$parsedSource) {
            $$parsedSource["suggestions"] = $$createField4_0($$parsedSource["suggestions"]);
        }
        return new PermissionRequest(/** @type {Partial<PermissionRequest>} */($$parsedSource));
    }
}

/**
 * PermissionUpdate is a provider-authored rule update. Claude supplies these
 * suggestions for an "always allow" decision; keeping the structure opaque
 * lets newer CLI versions add rule variants without requiring an app release.
 * @typedef {{ [_ in string]?: any }} PermissionUpdate
 */

/**
 * Result is the terminal outcome of a completed run.
 */
export class Result {
    /**
     * Creates a new Result instance.
     * @param {Partial<Result>} [$$source = {}] - The source object to create the Result.
     */
    constructor($$source = {}) {
        if (!("finalMessage" in $$source)) {
            /**
             * FinalMessage is the agent's last assistant message — the natural-language
             * summary of what it did.
             * @member
             * @type {string}
             */
            this["finalMessage"] = "";
        }
        if (!("usage" in $$source)) {
            /**
             * Usage is best-effort token accounting; zero when the runtime omits it.
             * @member
             * @type {Usage}
             */
            this["usage"] = (new Usage());
        }
        if (/** @type {any} */(false)) {
            /**
             * SessionID is the runtime's own session/thread id, for resuming.
             * @member
             * @type {string | undefined}
             */
            this["sessionId"] = undefined;
        }
        if (!("succeeded" in $$source)) {
            /**
             * Succeeded is true when the runtime reported a clean terminal state.
             * @member
             * @type {boolean}
             */
            this["succeeded"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Result}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("usage" in $$parsedSource) {
            $$parsedSource["usage"] = $$createField1_0($$parsedSource["usage"]);
        }
        return new Result(/** @type {Partial<Result>} */($$parsedSource));
    }
}

/**
 * Runtime identifies a local agent CLI the engine knows how to drive.
 * @readonly
 * @enum {string}
 */
export const Runtime = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * RuntimeCodex drives the OpenAI Codex CLI via app-server.
     */
    RuntimeCodex: "codex",

    /**
     * RuntimeClaude drives Anthropic's Claude Code via `claude -p`.
     */
    RuntimeClaude: "claude",

    /**
     * RuntimeModu drives Modu Code via its non-interactive print mode.
     */
    RuntimeModu: "modu",
};

/**
 * StreamPhase describes how an event contributes to one logical, growing UI
 * entry. Empty means the event is atomic and remains backwards compatible with
 * events produced before streaming was introduced.
 * @readonly
 * @enum {string}
 */
export const StreamPhase = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    StreamStart: "start",
    StreamDelta: "delta",
    StreamSnapshot: "snapshot",
    StreamEnd: "end",
};

/**
 * Usage captures cumulative token accounting for one workflow step. InputTokens
 * includes cache reads and cache creation when a provider reports them
 * separately; the detailed fields are subsets used to explain that total.
 */
export class Usage {
    /**
     * Creates a new Usage instance.
     * @param {Partial<Usage>} [$$source = {}] - The source object to create the Usage.
     */
    constructor($$source = {}) {
        if (!("inputTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["inputTokens"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["cachedInputTokens"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["cacheCreationInputTokens"] = undefined;
        }
        if (!("outputTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["outputTokens"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["reasoningOutputTokens"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Usage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Usage}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Usage(/** @type {Partial<Usage>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ClaudeModelInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = CodexModelInfo.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = CodexServiceTier.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = PermissionRequest.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = $Create.Map($Create.Any, $Create.Any);
var $$createType10 = /** @type {(...args: any[]) => any} */(function $$initCreateType10(...args) {
    if ($$createType10 === $$initCreateType10) {
        $$createType10 = $$createType9;
    }
    return $$createType10(...args);
});
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = Usage.createFrom;
