// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as worker$0 from "../worker/models.js";

export class PermissionDecisionInput {
    /**
     * Creates a new PermissionDecisionInput instance.
     * @param {Partial<PermissionDecisionInput>} [$$source = {}] - The source object to create the PermissionDecisionInput.
     */
    constructor($$source = {}) {
        if (!("runId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["runId"] = "";
        }
        if (!("requestId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["requestId"] = "";
        }
        if (!("decision" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["decision"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PermissionDecisionInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PermissionDecisionInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PermissionDecisionInput(/** @type {Partial<PermissionDecisionInput>} */($$parsedSource));
    }
}

export const RunView = worker$0.SharedRun;

/**
 * @typedef {worker$0.SharedRun} RunView
 */

export class StartRunInput {
    /**
     * Creates a new StartRunInput instance.
     * @param {Partial<StartRunInput>} [$$source = {}] - The source object to create the StartRunInput.
     */
    constructor($$source = {}) {
        if (!("workerId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["workerId"] = "";
        }
        if (!("workspaceId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["workspaceId"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["conversationId"] = undefined;
        }
        if (!("runtime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["runtime"] = "";
        }
        if (!("prompt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["prompt"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["model"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["reasoningEffort"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["serviceTier"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["provider"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["resumeSessionId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["timeoutSeconds"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartRunInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StartRunInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StartRunInput(/** @type {Partial<StartRunInput>} */($$parsedSource));
    }
}

export class WorkerStatus {
    /**
     * Creates a new WorkerStatus instance.
     * @param {Partial<WorkerStatus>} [$$source = {}] - The source object to create the WorkerStatus.
     */
    constructor($$source = {}) {
        if (!("worker" in $$source)) {
            /**
             * @member
             * @type {worker$0.Info}
             */
            this["worker"] = (new worker$0.Info());
        }
        if (!("health" in $$source)) {
            /**
             * @member
             * @type {worker$0.Health}
             */
            this["health"] = (new worker$0.Health());
        }
        if (!("checkedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["checkedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("latencyMilliseconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["latencyMilliseconds"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkerStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WorkerStatus}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("worker" in $$parsedSource) {
            $$parsedSource["worker"] = $$createField0_0($$parsedSource["worker"]);
        }
        if ("health" in $$parsedSource) {
            $$parsedSource["health"] = $$createField1_0($$parsedSource["health"]);
        }
        return new WorkerStatus(/** @type {Partial<WorkerStatus>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = worker$0.Info.createFrom;
const $$createType1 = worker$0.Health.createFrom;
