// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Definition is an editable workflow template. Each Run persists a complete
 * snapshot so later template edits cannot alter active or historical runs.
 */
export class Definition {
    /**
     * Creates a new Definition instance.
     * @param {Partial<Definition>} [$$source = {}] - The source object to create the Definition.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["mode"] = undefined;
        }
        if (!("entryStepId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["entryStepId"] = "";
        }
        if (!("steps" in $$source)) {
            /**
             * @member
             * @type {Step[]}
             */
            this["steps"] = [];
        }
        if (!("policy" in $$source)) {
            /**
             * @member
             * @type {Policy}
             */
            this["policy"] = (new Policy());
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Layout | undefined}
             */
            this["layout"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["createdAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["updatedAt"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Definition instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Definition}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType1;
        const $$createField6_0 = $$createType2;
        const $$createField7_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("steps" in $$parsedSource) {
            $$parsedSource["steps"] = $$createField5_0($$parsedSource["steps"]);
        }
        if ("policy" in $$parsedSource) {
            $$parsedSource["policy"] = $$createField6_0($$parsedSource["policy"]);
        }
        if ("layout" in $$parsedSource) {
            $$parsedSource["layout"] = $$createField7_0($$parsedSource["layout"]);
        }
        return new Definition(/** @type {Partial<Definition>} */($$parsedSource));
    }
}

/**
 * Instruction is durable human guidance queued while an Agent step is active.
 * It lives in a file separate from run.json so enqueueing cannot race the Run
 * revision used by the workflow state machine.
 */
export class Instruction {
    /**
     * Creates a new Instruction instance.
     * @param {Partial<Instruction>} [$$source = {}] - The source object to create the Instruction.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["attachments"] = undefined;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {InstructionStatus}
             */
            this["status"] = InstructionStatus.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["priority"] = undefined;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["appliedAt"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Instruction instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Instruction}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("attachments" in $$parsedSource) {
            $$parsedSource["attachments"] = $$createField2_0($$parsedSource["attachments"]);
        }
        return new Instruction(/** @type {Partial<Instruction>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const InstructionStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    InstructionPending: "pending",
    InstructionApplied: "applied",
    InstructionRemoved: "removed",
};

export class Layout {
    /**
     * Creates a new Layout instance.
     * @param {Partial<Layout>} [$$source = {}] - The source object to create the Layout.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: Point } | undefined}
             */
            this["nodes"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Layout instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Layout}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("nodes" in $$parsedSource) {
            $$parsedSource["nodes"] = $$createField0_0($$parsedSource["nodes"]);
        }
        return new Layout(/** @type {Partial<Layout>} */($$parsedSource));
    }
}

export class NodeState {
    /**
     * Creates a new NodeState instance.
     * @param {Partial<NodeState>} [$$source = {}] - The source object to create the NodeState.
     */
    constructor($$source = {}) {
        if (!("stepId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["stepId"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {NodeStatus}
             */
            this["status"] = NodeStatus.$zero;
        }
        if (!("attempt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["attempt"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["signal"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["content"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["startedAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["finishedAt"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NodeState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NodeState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NodeState(/** @type {Partial<NodeState>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const NodeStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    NodePending: "pending",
    NodeRunning: "running",
    NodeCompleted: "completed",
    NodePaused: "paused",
    NodeFailed: "failed",
};

export class Point {
    /**
     * Creates a new Point instance.
     * @param {Partial<Point>} [$$source = {}] - The source object to create the Point.
     */
    constructor($$source = {}) {
        if (!("x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["y"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Point instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Point}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Point(/** @type {Partial<Point>} */($$parsedSource));
    }
}

/**
 * Policy bounds automatic execution. Zero values are filled by Normalize.
 */
export class Policy {
    /**
     * Creates a new Policy instance.
     * @param {Partial<Policy>} [$$source = {}] - The source object to create the Policy.
     */
    constructor($$source = {}) {
        if (!("maxTransitions" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxTransitions"] = 0;
        }
        if (!("maxConsecutiveFailures" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxConsecutiveFailures"] = 0;
        }
        if (!("stepTimeoutSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["stepTimeoutSeconds"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Policy instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Policy}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Policy(/** @type {Partial<Policy>} */($$parsedSource));
    }
}

export class ResolvedRuntimeSettings {
    /**
     * Creates a new ResolvedRuntimeSettings instance.
     * @param {Partial<ResolvedRuntimeSettings>} [$$source = {}] - The source object to create the ResolvedRuntimeSettings.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["environmentAllowlist"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["provider"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["reasoningEffort"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["serviceTier"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["maxContextWindow"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResolvedRuntimeSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ResolvedRuntimeSettings}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("environmentAllowlist" in $$parsedSource) {
            $$parsedSource["environmentAllowlist"] = $$createField0_0($$parsedSource["environmentAllowlist"]);
        }
        return new ResolvedRuntimeSettings(/** @type {Partial<ResolvedRuntimeSettings>} */($$parsedSource));
    }
}

/**
 * Run is the durable state needed to resume orchestration. Runtime sessions
 * are keyed by step ID so revisiting a role resumes only that role's context.
 */
export class Run {
    /**
     * Creates a new Run instance.
     * @param {Partial<Run>} [$$source = {}] - The source object to create the Run.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("taskId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["taskId"] = "";
        }
        if (!("workflowId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["workflowId"] = "";
        }
        if (!("revision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["revision"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {RunStatus}
             */
            this["status"] = RunStatus.$zero;
        }
        if (!("currentStepId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentStepId"] = "";
        }
        if (!("transitionCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["transitionCount"] = 0;
        }
        if (!("consecutiveFailures" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["consecutiveFailures"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["sessions"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {TransitionRecord[] | undefined}
             */
            this["history"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: NodeState } | undefined}
             */
            this["nodes"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["pauseReason"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastError"] = undefined;
        }
        if (!("startedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["startedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["completedAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["maxLocalDAGConcurrency"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["interruptGraceSeconds"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: ResolvedRuntimeSettings } | undefined}
             */
            this["runtimeSettings"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Run instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Run}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType7;
        const $$createField9_0 = $$createType9;
        const $$createField10_0 = $$createType11;
        const $$createField18_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sessions" in $$parsedSource) {
            $$parsedSource["sessions"] = $$createField8_0($$parsedSource["sessions"]);
        }
        if ("history" in $$parsedSource) {
            $$parsedSource["history"] = $$createField9_0($$parsedSource["history"]);
        }
        if ("nodes" in $$parsedSource) {
            $$parsedSource["nodes"] = $$createField10_0($$parsedSource["nodes"]);
        }
        if ("runtimeSettings" in $$parsedSource) {
            $$parsedSource["runtimeSettings"] = $$createField18_0($$parsedSource["runtimeSettings"]);
        }
        return new Run(/** @type {Partial<Run>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const RunStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    RunReady: "ready",
    RunRunning: "running",
    RunPaused: "paused",
    RunCompleted: "completed",
    RunFailed: "failed",
    RunCancelled: "cancelled",
};

/**
 * Step is one serial Agent turn in a workflow. Runtime is resolved by the
 * local runtime registry; the domain layer deliberately does not depend on CLI
 * adapters.
 */
export class Step {
    /**
     * Creates a new Step instance.
     * @param {Partial<Step>} [$$source = {}] - The source object to create the Step.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("runtime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["runtime"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["model"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["sandbox"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["workerId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["dependsOn"] = undefined;
        }
        if (!("rolePrompt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["rolePrompt"] = "";
        }
        if (!("instruction" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["instruction"] = "";
        }
        if (!("transitions" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["transitions"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Step instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Step}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType4;
        const $$createField9_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("dependsOn" in $$parsedSource) {
            $$parsedSource["dependsOn"] = $$createField6_0($$parsedSource["dependsOn"]);
        }
        if ("transitions" in $$parsedSource) {
            $$parsedSource["transitions"] = $$createField9_0($$parsedSource["transitions"]);
        }
        return new Step(/** @type {Partial<Step>} */($$parsedSource));
    }
}

/**
 * StepRun is one attempt to execute one workflow step.
 */
export class StepRun {
    /**
     * Creates a new StepRun instance.
     * @param {Partial<StepRun>} [$$source = {}] - The source object to create the StepRun.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("runId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["runId"] = "";
        }
        if (!("stepId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["stepId"] = "";
        }
        if (!("attempt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["attempt"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {StepRunStatus}
             */
            this["status"] = StepRunStatus.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["signal"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["content"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["sessionIdBefore"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["sessionIdAfter"] = undefined;
        }
        if (!("startedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["startedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["finishedAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["inputTokens"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["cachedInputTokens"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["cacheCreationInputTokens"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["outputTokens"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["reasoningOutputTokens"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * ContextWindow and ContextTokens describe how full the model's context
             * was, which the token counters above cannot express: those accumulate
             * across every model call in the step, while the window only ever held one
             * prompt. ContextTokens may fall between attempts when the harness compacts.
             * @member
             * @type {number | undefined}
             */
            this["contextWindow"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["contextTokens"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["durationMs"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StepRun instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StepRun}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StepRun(/** @type {Partial<StepRun>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const StepRunStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    StepRunRunning: "running",
    StepRunSucceeded: "succeeded",
    StepRunFailed: "failed",
    StepRunInterrupted: "interrupted",
};

export class TransitionRecord {
    /**
     * Creates a new TransitionRecord instance.
     * @param {Partial<TransitionRecord>} [$$source = {}] - The source object to create the TransitionRecord.
     */
    constructor($$source = {}) {
        if (!("fromStepId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fromStepId"] = "";
        }
        if (!("signal" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["signal"] = "";
        }
        if (!("target" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["target"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TransitionRecord instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TransitionRecord}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TransitionRecord(/** @type {Partial<TransitionRecord>} */($$parsedSource));
    }
}

export class ValidationIssue {
    /**
     * Creates a new ValidationIssue instance.
     * @param {Partial<ValidationIssue>} [$$source = {}] - The source object to create the ValidationIssue.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ValidationIssue instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ValidationIssue}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ValidationIssue(/** @type {Partial<ValidationIssue>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Step.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = Policy.createFrom;
const $$createType3 = Layout.createFrom;
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = Point.createFrom;
const $$createType6 = $Create.Map($Create.Any, $$createType5);
const $$createType7 = $Create.Map($Create.Any, $Create.Any);
const $$createType8 = TransitionRecord.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = NodeState.createFrom;
const $$createType11 = $Create.Map($Create.Any, $$createType10);
const $$createType12 = ResolvedRuntimeSettings.createFrom;
const $$createType13 = $Create.Map($Create.Any, $$createType12);
