// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class GitBranch {
    /**
     * Creates a new GitBranch instance.
     * @param {Partial<GitBranch>} [$$source = {}] - The source object to create the GitBranch.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("current" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["current"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["upstream"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitBranch instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GitBranch}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitBranch(/** @type {Partial<GitBranch>} */($$parsedSource));
    }
}

export class GitFile {
    /**
     * Creates a new GitFile instance.
     * @param {Partial<GitFile>} [$$source = {}] - The source object to create the GitFile.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("index" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["index"] = "";
        }
        if (!("worktree" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["worktree"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitFile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GitFile}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitFile(/** @type {Partial<GitFile>} */($$parsedSource));
    }
}

export class GitSnapshot {
    /**
     * Creates a new GitSnapshot instance.
     * @param {Partial<GitSnapshot>} [$$source = {}] - The source object to create the GitSnapshot.
     */
    constructor($$source = {}) {
        if (!("isRepo" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isRepo"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["head"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["branch"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["ahead"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["behind"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["status"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["diffStat"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["stagedStat"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {GitFile[] | undefined}
             */
            this["files"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitSnapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GitSnapshot}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField8_0($$parsedSource["files"]);
        }
        return new GitSnapshot(/** @type {Partial<GitSnapshot>} */($$parsedSource));
    }
}

/**
 * RemoteFS identifies a directory reached through the user's OpenSSH
 * configuration. The local Agent keeps running on this machine; only its
 * command and filesystem operations are redirected to this target.
 */
export class RemoteFS {
    /**
     * Creates a new RemoteFS instance.
     * @param {Partial<RemoteFS>} [$$source = {}] - The source object to create the RemoteFS.
     */
    constructor($$source = {}) {
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("root" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["root"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["username"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["credentialId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["sshOptions"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoteFS instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RemoteFS}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sshOptions" in $$parsedSource) {
            $$parsedSource["sshOptions"] = $$createField4_0($$parsedSource["sshOptions"]);
        }
        return new RemoteFS(/** @type {Partial<RemoteFS>} */($$parsedSource));
    }
}

export class Workspace {
    /**
     * Creates a new Workspace instance.
     * @param {Partial<Workspace>} [$$source = {}] - The source object to create the Workspace.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {RemoteFS | null | undefined}
             */
            this["remoteFs"] = undefined;
        }
        if (!("defaultSandbox" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["defaultSandbox"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["pinned"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["hidden"] = undefined;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("lastOpenedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastOpenedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Workspace instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Workspace}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("remoteFs" in $$parsedSource) {
            $$parsedSource["remoteFs"] = $$createField3_0($$parsedSource["remoteFs"]);
        }
        return new Workspace(/** @type {Partial<Workspace>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = GitFile.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = RemoteFS.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
