// The marketing site and the desktop application must not drift apart on
// colour. Rather than keeping a second copy of the palette by hand, this lifts
// the marked range straight out of the application's stylesheet.
//
// The direction is deliberate: the application owns the palette, the site
// follows. Editing the generated file is pointless — the next dev/build run
// overwrites it — so change frontend/src/index.css instead.
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const source = resolve(here, "../../frontend/src/index.css");
const target = resolve(here, "../src/styles/tokens.generated.css");

const START = "/* brand-tokens:start";
const END = "/* brand-tokens:end */";

const css = await readFile(source, "utf8");

const startIndex = css.indexOf(START);
const endIndex = css.indexOf(END);
if (startIndex === -1 || endIndex === -1 || endIndex < startIndex) {
  // Failing loudly beats emitting an empty palette and shipping a site that
  // renders black text on a black ground.
  throw new Error(
    `could not find the brand-tokens markers in ${relative(process.cwd(), source)}. ` +
      "Both `/* brand-tokens:start` and `/* brand-tokens:end */` must be present.",
  );
}

const block = css.slice(startIndex, endIndex + END.length).trimEnd();

const banner = `/* Generated by web/scripts/sync-tokens.mjs — do not edit.
   Source of truth: frontend/src/index.css (the brand-tokens block).
   Regenerated on every \`npm run dev\` and \`npm run build\`. */\n\n`;

await mkdir(dirname(target), { recursive: true });
await writeFile(target, banner + block + "\n", "utf8");

const tokenCount = (block.match(/^\s*--[\w-]+:/gm) || []).length;
console.log(`sync-tokens: ${tokenCount} declarations → ${relative(process.cwd(), target)}`);
