// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * EventKind is the normalized category of a streamed run event. It is the
 * common denominator across every supported runtime.
 * @readonly
 * @enum {string}
 */
export const EventKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * KindStarted marks the beginning of a run (session/thread established).
     */
    KindStarted: "started",

    /**
     * KindReasoning carries the agent's private thinking, when the runtime
     * surfaces it. Useful for live progress but not part of the deliverable.
     */
    KindReasoning: "reasoning",

    /**
     * KindMessage carries assistant prose addressed to the user.
     */
    KindMessage: "message",

    /**
     * KindToolUse marks the agent invoking a tool (shell command, file edit).
     */
    KindToolUse: "tool_use",

    /**
     * KindToolResult carries the result of a prior tool invocation.
     */
    KindToolResult: "tool_result",

    /**
     * KindFileChange marks the agent creating or modifying a file.
     */
    KindFileChange: "file_change",

    /**
     * KindUsage carries token/cost accounting for the turn.
     */
    KindUsage: "usage",

    /**
     * KindResult marks the terminal outcome of the run.
     */
    KindResult: "result",

    /**
     * KindError carries a runtime or parse error encountered mid-stream.
     */
    KindError: "error",
};

/**
 * StreamPhase describes how an event contributes to one logical, growing UI
 * entry. Empty means the event is atomic and remains backwards compatible with
 * events produced before streaming was introduced.
 * @readonly
 * @enum {string}
 */
export const StreamPhase = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    StreamStart: "start",
    StreamDelta: "delta",
    StreamSnapshot: "snapshot",
    StreamEnd: "end",
};
