// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ClaudeConfiguration {
    /**
     * Creates a new ClaudeConfiguration instance.
     * @param {Partial<ClaudeConfiguration>} [$$source = {}] - The source object to create the ClaudeConfiguration.
     */
    constructor($$source = {}) {
        if (!("models" in $$source)) {
            /**
             * @member
             * @type {ClaudeModelInfo[]}
             */
            this["models"] = [];
        }
        if (!("efforts" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["efforts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClaudeConfiguration instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ClaudeConfiguration}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField0_0($$parsedSource["models"]);
        }
        if ("efforts" in $$parsedSource) {
            $$parsedSource["efforts"] = $$createField1_0($$parsedSource["efforts"]);
        }
        return new ClaudeConfiguration(/** @type {Partial<ClaudeConfiguration>} */($$parsedSource));
    }
}

export class ClaudeModelInfo {
    /**
     * Creates a new ClaudeModelInfo instance.
     * @param {Partial<ClaudeModelInfo>} [$$source = {}] - The source object to create the ClaudeModelInfo.
     */
    constructor($$source = {}) {
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("displayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }
        if (!("alias" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["alias"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClaudeModelInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ClaudeModelInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClaudeModelInfo(/** @type {Partial<ClaudeModelInfo>} */($$parsedSource));
    }
}

export class CodexConfiguration {
    /**
     * Creates a new CodexConfiguration instance.
     * @param {Partial<CodexConfiguration>} [$$source = {}] - The source object to create the CodexConfiguration.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["model"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["reasoningEffort"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["serviceTier"] = undefined;
        }
        if (!("models" in $$source)) {
            /**
             * @member
             * @type {CodexModelInfo[]}
             */
            this["models"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CodexConfiguration instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CodexConfiguration}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField3_0($$parsedSource["models"]);
        }
        return new CodexConfiguration(/** @type {Partial<CodexConfiguration>} */($$parsedSource));
    }
}

export class CodexModelInfo {
    /**
     * Creates a new CodexModelInfo instance.
     * @param {Partial<CodexModelInfo>} [$$source = {}] - The source object to create the CodexModelInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("displayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (!("defaultReasoningEffort" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["defaultReasoningEffort"] = "";
        }
        if (!("reasoningEfforts" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["reasoningEfforts"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {CodexServiceTier[] | undefined}
             */
            this["serviceTiers"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["defaultServiceTier"] = undefined;
        }
        if (!("isDefault" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDefault"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CodexModelInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CodexModelInfo}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType2;
        const $$createField6_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("reasoningEfforts" in $$parsedSource) {
            $$parsedSource["reasoningEfforts"] = $$createField5_0($$parsedSource["reasoningEfforts"]);
        }
        if ("serviceTiers" in $$parsedSource) {
            $$parsedSource["serviceTiers"] = $$createField6_0($$parsedSource["serviceTiers"]);
        }
        return new CodexModelInfo(/** @type {Partial<CodexModelInfo>} */($$parsedSource));
    }
}

export class CodexServiceTier {
    /**
     * Creates a new CodexServiceTier instance.
     * @param {Partial<CodexServiceTier>} [$$source = {}] - The source object to create the CodexServiceTier.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CodexServiceTier instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CodexServiceTier}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CodexServiceTier(/** @type {Partial<CodexServiceTier>} */($$parsedSource));
    }
}

/**
 * EventKind is the normalized category of a streamed run event. It is the
 * common denominator across every supported runtime.
 * @readonly
 * @enum {string}
 */
export const EventKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * KindStarted marks the beginning of a run (session/thread established).
     */
    KindStarted: "started",

    /**
     * KindReasoning carries the agent's private thinking, when the runtime
     * surfaces it. Useful for live progress but not part of the deliverable.
     */
    KindReasoning: "reasoning",

    /**
     * KindMessage carries assistant prose addressed to the user.
     */
    KindMessage: "message",

    /**
     * KindToolUse marks the agent invoking a tool (shell command, file edit).
     */
    KindToolUse: "tool_use",

    /**
     * KindToolResult carries the result of a prior tool invocation.
     */
    KindToolResult: "tool_result",

    /**
     * KindFileChange marks the agent creating or modifying a file.
     */
    KindFileChange: "file_change",

    /**
     * KindUsage carries token/cost accounting for the turn.
     */
    KindUsage: "usage",

    /**
     * KindResult marks the terminal outcome of the run.
     */
    KindResult: "result",

    /**
     * KindError carries a runtime or parse error encountered mid-stream.
     */
    KindError: "error",
};

/**
 * StreamPhase describes how an event contributes to one logical, growing UI
 * entry. Empty means the event is atomic and remains backwards compatible with
 * events produced before streaming was introduced.
 * @readonly
 * @enum {string}
 */
export const StreamPhase = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    StreamStart: "start",
    StreamDelta: "delta",
    StreamSnapshot: "snapshot",
    StreamEnd: "end",
};

// Private type creation functions
const $$createType0 = ClaudeModelInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = CodexModelInfo.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = CodexServiceTier.createFrom;
const $$createType6 = $Create.Array($$createType5);
