// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ClaudeConfiguration {
    /**
     * Creates a new ClaudeConfiguration instance.
     * @param {Partial<ClaudeConfiguration>} [$$source = {}] - The source object to create the ClaudeConfiguration.
     */
    constructor($$source = {}) {
        if (!("models" in $$source)) {
            /**
             * @member
             * @type {ClaudeModelInfo[]}
             */
            this["models"] = [];
        }
        if (!("efforts" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["efforts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClaudeConfiguration instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ClaudeConfiguration}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField0_0($$parsedSource["models"]);
        }
        if ("efforts" in $$parsedSource) {
            $$parsedSource["efforts"] = $$createField1_0($$parsedSource["efforts"]);
        }
        return new ClaudeConfiguration(/** @type {Partial<ClaudeConfiguration>} */($$parsedSource));
    }
}

export class ClaudeModelInfo {
    /**
     * Creates a new ClaudeModelInfo instance.
     * @param {Partial<ClaudeModelInfo>} [$$source = {}] - The source object to create the ClaudeModelInfo.
     */
    constructor($$source = {}) {
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("displayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }
        if (!("alias" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["alias"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClaudeModelInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ClaudeModelInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClaudeModelInfo(/** @type {Partial<ClaudeModelInfo>} */($$parsedSource));
    }
}

export class CodexConfiguration {
    /**
     * Creates a new CodexConfiguration instance.
     * @param {Partial<CodexConfiguration>} [$$source = {}] - The source object to create the CodexConfiguration.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["model"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["reasoningEffort"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["serviceTier"] = undefined;
        }
        if (!("models" in $$source)) {
            /**
             * @member
             * @type {CodexModelInfo[]}
             */
            this["models"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CodexConfiguration instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CodexConfiguration}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField3_0($$parsedSource["models"]);
        }
        return new CodexConfiguration(/** @type {Partial<CodexConfiguration>} */($$parsedSource));
    }
}

export class CodexModelInfo {
    /**
     * Creates a new CodexModelInfo instance.
     * @param {Partial<CodexModelInfo>} [$$source = {}] - The source object to create the CodexModelInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("displayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (!("defaultReasoningEffort" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["defaultReasoningEffort"] = "";
        }
        if (!("reasoningEfforts" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["reasoningEfforts"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {CodexServiceTier[] | undefined}
             */
            this["serviceTiers"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["defaultServiceTier"] = undefined;
        }
        if (!("isDefault" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDefault"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CodexModelInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CodexModelInfo}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType2;
        const $$createField6_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("reasoningEfforts" in $$parsedSource) {
            $$parsedSource["reasoningEfforts"] = $$createField5_0($$parsedSource["reasoningEfforts"]);
        }
        if ("serviceTiers" in $$parsedSource) {
            $$parsedSource["serviceTiers"] = $$createField6_0($$parsedSource["serviceTiers"]);
        }
        return new CodexModelInfo(/** @type {Partial<CodexModelInfo>} */($$parsedSource));
    }
}

export class CodexServiceTier {
    /**
     * Creates a new CodexServiceTier instance.
     * @param {Partial<CodexServiceTier>} [$$source = {}] - The source object to create the CodexServiceTier.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CodexServiceTier instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CodexServiceTier}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CodexServiceTier(/** @type {Partial<CodexServiceTier>} */($$parsedSource));
    }
}

/**
 * CodexSkill is one enabled Skill discovered by Codex for a working directory.
 * Name is the token users invoke after '$'; Path is sent back to app-server as
 * an explicit skill input so Codex does not need to resolve the marker again.
 */
export class CodexSkill {
    /**
     * Creates a new CodexSkill instance.
     * @param {Partial<CodexSkill>} [$$source = {}] - The source object to create the CodexSkill.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["displayName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["shortDescription"] = undefined;
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["scope"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CodexSkill instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CodexSkill}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CodexSkill(/** @type {Partial<CodexSkill>} */($$parsedSource));
    }
}

/**
 * ContextUsage reports how full the model's context window is. It is a
 * different quantity from [Usage] and the two must not be substituted for one
 * another: Usage accumulates every model call in a step, so it only ever grows
 * and routinely exceeds the window a tool-heavy step never came close to
 * filling. Occupancy is the size of a single prompt, and it *falls* whenever
 * the harness compacts. Charting the cumulative total against the window shows
 * a step at 300% of a context it never overflowed.
 */
export class ContextUsage {
    /**
     * Creates a new ContextUsage instance.
     * @param {Partial<ContextUsage>} [$$source = {}] - The source object to create the ContextUsage.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * Window is the model's context window in tokens. Zero means the runtime
             * did not report one — render that as unknown rather than as a full bar.
             * @member
             * @type {number | undefined}
             */
            this["window"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Tokens is the prompt size of the most recent model call: everything the
             * model read this turn, cached prefix included, because a cache hit still
             * occupies the window. May decrease after a compaction.
             * @member
             * @type {number | undefined}
             */
            this["tokens"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContextUsage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ContextUsage}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ContextUsage(/** @type {Partial<ContextUsage>} */($$parsedSource));
    }
}

/**
 * Event is a single normalized step emitted while an agent runs. Raw preserves
 * the original JSON line so nothing is lost, while Kind/Text give callers a
 * runtime-agnostic view suitable for display and persistence.
 */
export class Event {
    /**
     * Creates a new Event instance.
     * @param {Partial<Event>} [$$source = {}] - The source object to create the Event.
     */
    constructor($$source = {}) {
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {EventKind}
             */
            this["kind"] = EventKind.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * Usage is the latest cumulative token accounting for this step. Runtimes
             * that report usage before completion attach it to KindUsage so the desktop
             * can update its metrics while the agent is still running.
             * @member
             * @type {Usage | null | undefined}
             */
            this["usage"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * StreamID is stable for all chunks belonging to one logical message,
             * reasoning block, or tool output. Empty identifies an atomic event.
             * @member
             * @type {string | undefined}
             */
            this["streamId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Phase controls whether Text starts, appends to, replaces, or completes a
             * logical stream. Revision is assigned by the orchestration collector after
             * it batches provider token deltas.
             * @member
             * @type {StreamPhase | undefined}
             */
            this["phase"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["revision"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Text is the human-meaningful payload: message prose, command, file path,
             * or error description, depending on Kind.
             * @member
             * @type {string | undefined}
             */
            this["text"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Raw is the original JSONL line from the runtime, retained for debugging
             * and forward compatibility with fields we do not yet model.
             * @member
             * @type {string | undefined}
             */
            this["raw"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Failed reports that this individual event is an error: a tool that
             * returned an error, not a run that ended badly. A step can fail while most
             * of its tool calls succeeded, so callers must not infer one from the other.
             * @member
             * @type {boolean | undefined}
             */
            this["failed"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Context is the context-window occupancy observed at this step, attached
             * to KindUsage beside Usage. It is a separate field precisely because it
             * is not a subset of Usage — see [ContextUsage].
             * @member
             * @type {ContextUsage | null | undefined}
             */
            this["context"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Permission is populated for permission_request and permission_resolved
             * events. PermissionDecision is "allow" or "deny" on the resolved event.
             * @member
             * @type {PermissionRequest | null | undefined}
             */
            this["permission"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["permissionDecision"] = undefined;
        }
        if (!("at" in $$source)) {
            /**
             * At is when the engine observed the event.
             * @member
             * @type {string}
             */
            this["at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Event instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Event}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType8;
        const $$createField8_0 = $$createType10;
        const $$createField9_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("usage" in $$parsedSource) {
            $$parsedSource["usage"] = $$createField1_0($$parsedSource["usage"]);
        }
        if ("context" in $$parsedSource) {
            $$parsedSource["context"] = $$createField8_0($$parsedSource["context"]);
        }
        if ("permission" in $$parsedSource) {
            $$parsedSource["permission"] = $$createField9_0($$parsedSource["permission"]);
        }
        return new Event(/** @type {Partial<Event>} */($$parsedSource));
    }
}

/**
 * EventKind is the normalized category of a streamed run event. It is the
 * common denominator across every supported runtime.
 * @readonly
 * @enum {string}
 */
export const EventKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * KindStarted marks the beginning of a run (session/thread established).
     */
    KindStarted: "started",

    /**
     * KindReasoning carries the agent's private thinking, when the runtime
     * surfaces it. Useful for live progress but not part of the deliverable.
     */
    KindReasoning: "reasoning",

    /**
     * KindMessage carries assistant prose addressed to the user.
     */
    KindMessage: "message",

    /**
     * KindToolUse marks the agent invoking a tool (shell command, file edit).
     */
    KindToolUse: "tool_use",

    /**
     * KindToolResult carries the result of a prior tool invocation.
     */
    KindToolResult: "tool_result",

    /**
     * KindFileChange marks the agent creating or modifying a file.
     */
    KindFileChange: "file_change",

    /**
     * KindUsage carries token/cost accounting for the turn.
     */
    KindUsage: "usage",

    /**
     * KindResult marks the terminal outcome of the run.
     */
    KindResult: "result",

    /**
     * KindError carries a runtime or parse error encountered mid-stream.
     */
    KindError: "error",

    /**
     * KindPermissionRequest asks the host application to approve or deny a
     * tool call while the runtime remains blocked on that decision.
     */
    KindPermissionRequest: "permission_request",

    /**
     * KindPermissionResolved records the decision returned to the runtime.
     */
    KindPermissionResolved: "permission_resolved",
};

/**
 * HarnessConfiguration is what a harness reports about itself when asked.
 */
export class HarnessConfiguration {
    /**
     * Creates a new HarnessConfiguration instance.
     * @param {Partial<HarnessConfiguration>} [$$source = {}] - The source object to create the HarnessConfiguration.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * Model is the harness's own current selection, when it reports one.
             * @member
             * @type {string | undefined}
             */
            this["model"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {HarnessModel[] | undefined}
             */
            this["models"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Efforts applies when a harness has one vocabulary for every model. A
             * model's own Efforts take precedence over this.
             * @member
             * @type {string[] | undefined}
             */
            this["efforts"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HarnessConfiguration instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HarnessConfiguration}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType14;
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField1_0($$parsedSource["models"]);
        }
        if ("efforts" in $$parsedSource) {
            $$parsedSource["efforts"] = $$createField2_0($$parsedSource["efforts"]);
        }
        return new HarnessConfiguration(/** @type {Partial<HarnessConfiguration>} */($$parsedSource));
    }
}

/**
 * HarnessModel is one model a harness advertises.
 */
export class HarnessModel {
    /**
     * Creates a new HarnessModel instance.
     * @param {Partial<HarnessModel>} [$$source = {}] - The source object to create the HarnessModel.
     */
    constructor($$source = {}) {
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("displayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Efforts is this model's own reasoning-effort vocabulary. Harnesses vary
             * it per model — Grok offers xhigh on 4.6 but not on 4.5 — so a single
             * harness-wide list would offer a level the model rejects.
             * @member
             * @type {string[] | undefined}
             */
            this["efforts"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * DefaultEffort is the level this model uses when none is chosen.
             * @member
             * @type {string | undefined}
             */
            this["defaultEffort"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * ContextWindow is the model's window in tokens, zero when the harness
             * does not report one. It is a property of the model rather than of the
             * run, which is why it rides the catalog instead of the event stream.
             * @member
             * @type {number | undefined}
             */
            this["contextWindow"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HarnessModel instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HarnessModel}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("efforts" in $$parsedSource) {
            $$parsedSource["efforts"] = $$createField3_0($$parsedSource["efforts"]);
        }
        return new HarnessModel(/** @type {Partial<HarnessModel>} */($$parsedSource));
    }
}

/**
 * PermissionRequest is the runtime-neutral payload shown by the desktop
 * approval card. ID identifies the blocking control request, while ToolUseID
 * identifies the eventual tool call in the provider transcript.
 */
export class PermissionRequest {
    /**
     * Creates a new PermissionRequest instance.
     * @param {Partial<PermissionRequest>} [$$source = {}] - The source object to create the PermissionRequest.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["toolUseId"] = undefined;
        }
        if (!("toolName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["toolName"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["input"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {PermissionUpdate[] | undefined}
             */
            this["suggestions"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["title"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["displayName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["decisionReason"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["suppressAlwaysAllow"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["requiresUserInteraction"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PermissionRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PermissionRequest}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType15;
        const $$createField4_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("input" in $$parsedSource) {
            $$parsedSource["input"] = $$createField3_0($$parsedSource["input"]);
        }
        if ("suggestions" in $$parsedSource) {
            $$parsedSource["suggestions"] = $$createField4_0($$parsedSource["suggestions"]);
        }
        return new PermissionRequest(/** @type {Partial<PermissionRequest>} */($$parsedSource));
    }
}

/**
 * PermissionUpdate is a provider-authored rule update. Claude supplies these
 * suggestions for an "always allow" decision; keeping the structure opaque
 * lets newer CLI versions add rule variants without requiring an app release.
 * @typedef {{ [_ in string]?: any }} PermissionUpdate
 */

/**
 * Result is the terminal outcome of a completed run.
 */
export class Result {
    /**
     * Creates a new Result instance.
     * @param {Partial<Result>} [$$source = {}] - The source object to create the Result.
     */
    constructor($$source = {}) {
        if (!("finalMessage" in $$source)) {
            /**
             * FinalMessage is the agent's last assistant message — the natural-language
             * summary of what it did.
             * @member
             * @type {string}
             */
            this["finalMessage"] = "";
        }
        if (!("usage" in $$source)) {
            /**
             * Usage is best-effort token accounting; zero when the runtime omits it.
             * @member
             * @type {Usage}
             */
            this["usage"] = (new Usage());
        }
        if (!("context" in $$source)) {
            /**
             * Context is the final context-window occupancy; zero when unreported.
             * @member
             * @type {ContextUsage}
             */
            this["context"] = (new ContextUsage());
        }
        if (/** @type {any} */(false)) {
            /**
             * SessionID is the runtime's own session/thread id, for resuming.
             * @member
             * @type {string | undefined}
             */
            this["sessionId"] = undefined;
        }
        if (!("succeeded" in $$source)) {
            /**
             * Succeeded is true when the runtime reported a clean terminal state.
             * @member
             * @type {boolean}
             */
            this["succeeded"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Result}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType7;
        const $$createField2_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("usage" in $$parsedSource) {
            $$parsedSource["usage"] = $$createField1_0($$parsedSource["usage"]);
        }
        if ("context" in $$parsedSource) {
            $$parsedSource["context"] = $$createField2_0($$parsedSource["context"]);
        }
        return new Result(/** @type {Partial<Result>} */($$parsedSource));
    }
}

/**
 * Runtime identifies a local agent CLI the engine knows how to drive.
 * @readonly
 * @enum {string}
 */
export const Runtime = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * RuntimeCodex drives the OpenAI Codex CLI via app-server.
     */
    RuntimeCodex: "codex",

    /**
     * RuntimeClaude drives Anthropic's Claude Code via `claude -p`.
     */
    RuntimeClaude: "claude",

    /**
     * RuntimeModu drives Modu Code via its native SDK or print mode.
     */
    RuntimeModu: "modu",

    /**
     * RuntimePi drives the Pi coding agent via `pi -p --mode json`.
     */
    RuntimePi: "pi",

    /**
     * RuntimeGrok drives xAI's Grok Build via its ACP server (`grok agent stdio`).
     */
    RuntimeGrok: "grok",

    /**
     * RuntimeDsh drives DeepSeek Harness via its one-shot headless profile.
     */
    RuntimeDsh: "dsh",
};

/**
 * StreamPhase describes how an event contributes to one logical, growing UI
 * entry. Empty means the event is atomic and remains backwards compatible with
 * events produced before streaming was introduced.
 * @readonly
 * @enum {string}
 */
export const StreamPhase = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    StreamStart: "start",
    StreamDelta: "delta",
    StreamSnapshot: "snapshot",
    StreamEnd: "end",
};

/**
 * Usage captures cumulative token accounting for one workflow step. InputTokens
 * includes cache reads and cache creation when a provider reports them
 * separately; the detailed fields are subsets used to explain that total.
 */
export class Usage {
    /**
     * Creates a new Usage instance.
     * @param {Partial<Usage>} [$$source = {}] - The source object to create the Usage.
     */
    constructor($$source = {}) {
        if (!("inputTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["inputTokens"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["cachedInputTokens"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["cacheCreationInputTokens"] = undefined;
        }
        if (!("outputTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["outputTokens"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["reasoningOutputTokens"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Usage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Usage}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Usage(/** @type {Partial<Usage>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ClaudeModelInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = CodexModelInfo.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = CodexServiceTier.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = Usage.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = ContextUsage.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = PermissionRequest.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = HarnessModel.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = $Create.Map($Create.Any, $Create.Any);
var $$createType16 = /** @type {(...args: any[]) => any} */(function $$initCreateType16(...args) {
    if ($$createType16 === $$initCreateType16) {
        $$createType16 = $$createType15;
    }
    return $$createType16(...args);
});
const $$createType17 = $Create.Array($$createType16);
