// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as workspaces$0 from "../../domain/workspaces/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mobile$0 from "../../service/mobile/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as worker$0 from "../../service/worker/models.js";

/**
 * @param {string} id
 * @returns {$CancellablePromise<mobile$0.WorkerStatus>}
 */
export function CheckWorker(id) {
    return $Call.ByID(503373925, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteWorker(id) {
    return $Call.ByID(60094852, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<mobile$0.RunView>}
 */
export function GetRun(id) {
    return $Call.ByID(42850800, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function InterruptRun(id) {
    return $Call.ByID(2935810917, id);
}

/**
 * @returns {$CancellablePromise<mobile$0.RunView[]>}
 */
export function ListRuns() {
    return $Call.ByID(2751141287).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<worker$0.Info[]>}
 */
export function ListWorkers() {
    return $Call.ByID(1285524968).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} workerID
 * @returns {$CancellablePromise<worker$0.WorkspaceMapping[]>}
 */
export function ListWorkspaces(workerID) {
    return $Call.ByID(2565852803, workerID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string} baseURL
 * @param {string} code
 * @returns {$CancellablePromise<worker$0.Info>}
 */
export function PairWorker(baseURL, code) {
    return $Call.ByID(1072201499, baseURL, code).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} workerID
 * @param {string} workspaceID
 * @param {worker$0.WorkspacePrepareRequest} input
 * @returns {$CancellablePromise<worker$0.WorkspacePrepareResult>}
 */
export function PrepareWorkspace(workerID, workspaceID, input) {
    return $Call.ByID(1084700857, workerID, workspaceID, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {string} workerID
 * @param {string} workspaceID
 * @param {boolean} deleteFiles
 * @returns {$CancellablePromise<void>}
 */
export function RemoveWorkspace(workerID, workspaceID, deleteFiles) {
    return $Call.ByID(1626531166, workerID, workspaceID, deleteFiles);
}

/**
 * @param {mobile$0.PermissionDecisionInput} input
 * @returns {$CancellablePromise<void>}
 */
export function RespondPermission(input) {
    return $Call.ByID(316387241, input);
}

/**
 * @param {mobile$0.StartRunInput} input
 * @returns {$CancellablePromise<mobile$0.RunView>}
 */
export function StartRun(input) {
    return $Call.ByID(2117250808, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} workerID
 * @param {string} workspaceID
 * @returns {$CancellablePromise<workspaces$0.GitSnapshot>}
 */
export function WorkspaceGitStatus(workerID, workspaceID) {
    return $Call.ByID(2980083104, workerID, workspaceID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

// Private type creation functions
const $$createType0 = mobile$0.WorkerStatus.createFrom;
const $$createType1 = mobile$0.RunView.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = worker$0.Info.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = worker$0.WorkspaceMapping.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = worker$0.WorkspacePrepareResult.createFrom;
const $$createType8 = workspaces$0.GitSnapshot.createFrom;
