// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as workspaces$0 from "../../domain/workspaces/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mobile$0 from "../../service/mobile/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as worker$0 from "../../service/worker/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agentrun$0 from "../../usecase/agentrun/models.js";

/**
 * AccountUsage reports one worker's quota and recent daily token activity.
 * @param {string} workerID
 * @param {boolean} refresh
 * @returns {$CancellablePromise<agentrun$0.AccountUsage[]>}
 */
export function AccountUsage(workerID, refresh) {
    return $Call.ByID(2381452179, workerID, refresh).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<mobile$0.WorkerStatus>}
 */
export function CheckWorker(id) {
    return $Call.ByID(503373925, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * DeleteConversation removes a session and every run in it.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteConversation(id) {
    return $Call.ByID(1273782921, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteWorker(id) {
    return $Call.ByID(60094852, id);
}

/**
 * DequeueFollowUp takes a queued message back out before the agent reaches it.
 * @param {string} runID
 * @param {string} instructionID
 * @returns {$CancellablePromise<worker$0.QueuedInstruction[]>}
 */
export function DequeueFollowUp(runID, instructionID) {
    return $Call.ByID(116216541, runID, instructionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<mobile$0.RunView>}
 */
export function GetRun(id) {
    return $Call.ByID(42850800, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function InterruptRun(id) {
    return $Call.ByID(2935810917, id);
}

/**
 * @returns {$CancellablePromise<mobile$0.RunView[]>}
 */
export function ListRunSummaries() {
    return $Call.ByID(1625646554).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @returns {$CancellablePromise<mobile$0.RunView[]>}
 */
export function ListRuns() {
    return $Call.ByID(2751141287).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @returns {$CancellablePromise<worker$0.Info[]>}
 */
export function ListWorkers() {
    return $Call.ByID(1285524968).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @param {string} workerID
 * @returns {$CancellablePromise<worker$0.WorkspaceMapping[]>}
 */
export function ListWorkspaces(workerID) {
    return $Call.ByID(2565852803, workerID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * LoadEarlierRun extends an open conversation one transcript page further back.
 * @param {string} id
 * @returns {$CancellablePromise<mobile$0.RunView>}
 */
export function LoadEarlierRun(id) {
    return $Call.ByID(913933000, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} baseURL
 * @param {string} code
 * @returns {$CancellablePromise<worker$0.Info>}
 */
export function PairWorker(baseURL, code) {
    return $Call.ByID(1072201499, baseURL, code).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {string} workerID
 * @param {string} workspaceID
 * @param {worker$0.WorkspacePrepareRequest} input
 * @returns {$CancellablePromise<worker$0.WorkspacePrepareResult>}
 */
export function PrepareWorkspace(workerID, workspaceID, input) {
    return $Call.ByID(1084700857, workerID, workspaceID, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * QueueFollowUp holds a message for a turn that is still running.
 * @param {string} runID
 * @param {string} prompt
 * @returns {$CancellablePromise<worker$0.QueuedInstruction[]>}
 */
export function QueueFollowUp(runID, prompt) {
    return $Call.ByID(1293369296, runID, prompt).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * RefreshRuns re-reads the host's history and waits for it, for pull to refresh.
 * @returns {$CancellablePromise<mobile$0.RunView[]>}
 */
export function RefreshRuns() {
    return $Call.ByID(3064858598).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string} workerID
 * @param {string} workspaceID
 * @param {boolean} deleteFiles
 * @returns {$CancellablePromise<void>}
 */
export function RemoveWorkspace(workerID, workspaceID, deleteFiles) {
    return $Call.ByID(1626531166, workerID, workspaceID, deleteFiles);
}

/**
 * RenameConversation retitles a session everywhere it is stored.
 * @param {string} id
 * @param {string} title
 * @returns {$CancellablePromise<void>}
 */
export function RenameConversation(id, title) {
    return $Call.ByID(2548765772, id, title);
}

/**
 * @param {mobile$0.PermissionDecisionInput} input
 * @returns {$CancellablePromise<void>}
 */
export function RespondPermission(input) {
    return $Call.ByID(316387241, input);
}

/**
 * @param {mobile$0.StartRunInput} input
 * @returns {$CancellablePromise<mobile$0.RunView>}
 */
export function StartRun(input) {
    return $Call.ByID(2117250808, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} workerID
 * @param {string} workspaceID
 * @returns {$CancellablePromise<workspaces$0.GitSnapshot>}
 */
export function WorkspaceGitStatus(workerID, workspaceID) {
    return $Call.ByID(2980083104, workerID, workspaceID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

// Private type creation functions
const $$createType0 = agentrun$0.AccountUsage.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = mobile$0.WorkerStatus.createFrom;
const $$createType3 = worker$0.QueuedInstruction.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = worker$0.SharedRun.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = worker$0.Info.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = worker$0.WorkspaceMapping.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = worker$0.WorkspacePrepareResult.createFrom;
const $$createType12 = workspaces$0.GitSnapshot.createFrom;
