// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class TerminalCreateInput {
    /**
     * Creates a new TerminalCreateInput instance.
     * @param {Partial<TerminalCreateInput>} [$$source = {}] - The source object to create the TerminalCreateInput.
     */
    constructor($$source = {}) {
        if (!("workspaceId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["workspaceId"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["shell"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["arguments"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["rows"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["cols"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalCreateInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TerminalCreateInput}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("arguments" in $$parsedSource) {
            $$parsedSource["arguments"] = $$createField2_0($$parsedSource["arguments"]);
        }
        return new TerminalCreateInput(/** @type {Partial<TerminalCreateInput>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
