// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../../domain/settings/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as desktop$0 from "../../service/desktop/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agentrun$0 from "../../usecase/agentrun/models.js";

/**
 * @param {desktop$0.RuntimeDraftInput} input
 * @returns {$CancellablePromise<desktop$0.RuntimeInfo>}
 */
export function CheckRuntimeDraft(input) {
    return $Call.ByID(626506285, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} previewToken
 * @returns {$CancellablePromise<desktop$0.CleanupResult>}
 */
export function ExecuteCleanup(previewToken) {
    return $Call.ByID(767148787, previewToken).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {desktop$0.DiagnosticsExportInput} input
 * @returns {$CancellablePromise<desktop$0.DiagnosticsExport>}
 */
export function ExportDiagnostics(input) {
    return $Call.ByID(2236013680, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<settings$0.Settings>}
 */
export function GetSettings() {
    return $Call.ByID(2147269751).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<desktop$0.StorageUsage>}
 */
export function GetStorageUsage() {
    return $Call.ByID(3275501654).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {settings$0.RuntimeSettings} input
 * @returns {$CancellablePromise<agentrun$0.ClaudeConfiguration>}
 */
export function InspectClaudeConfiguration(input) {
    return $Call.ByID(2020904538, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {settings$0.RuntimeSettings} input
 * @returns {$CancellablePromise<agentrun$0.CodexConfiguration>}
 */
export function InspectCodexConfiguration(input) {
    return $Call.ByID(1386021425, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * InspectHarnessConfiguration serves every harness that reports through the
 * shared configuration shape, so a new adapter needs no binding of its own.
 * @param {string} runtime
 * @param {settings$0.RuntimeSettings} input
 * @returns {$CancellablePromise<agentrun$0.HarnessConfiguration>}
 */
export function InspectHarnessConfiguration(runtime, input) {
    return $Call.ByID(3784350792, runtime, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {desktop$0.CleanupPreviewInput} input
 * @returns {$CancellablePromise<desktop$0.CleanupPreview>}
 */
export function PreviewCleanup(input) {
    return $Call.ByID(3009078482, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @param {string} section
 * @param {number} expectedRevision
 * @returns {$CancellablePromise<settings$0.Settings>}
 */
export function ResetSettingsSection(section, expectedRevision) {
    return $Call.ByID(1883644739, section, expectedRevision).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function RevealDataRoot() {
    return $Call.ByID(802031439);
}

/**
 * @param {settings$0.ExecutionSettings} input
 * @param {number} expectedRevision
 * @returns {$CancellablePromise<settings$0.Settings>}
 */
export function UpdateExecutionSettings(input, expectedRevision) {
    return $Call.ByID(1464442858, input, expectedRevision).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {settings$0.ExperimentalSettings} input
 * @param {number} expectedRevision
 * @returns {$CancellablePromise<settings$0.Settings>}
 */
export function UpdateExperimentalSettings(input, expectedRevision) {
    return $Call.ByID(1096196812, input, expectedRevision).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {{ [_ in string]?: settings$0.RuntimeSettings }} input
 * @param {number} expectedRevision
 * @returns {$CancellablePromise<settings$0.Settings>}
 */
export function UpdateRuntimeSettings(input, expectedRevision) {
    return $Call.ByID(2833699548, input, expectedRevision).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {settings$0.SecuritySettings} input
 * @param {number} expectedRevision
 * @returns {$CancellablePromise<settings$0.Settings>}
 */
export function UpdateSecuritySettings(input, expectedRevision) {
    return $Call.ByID(798710068, input, expectedRevision).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {settings$0.StorageSettings} input
 * @param {number} expectedRevision
 * @returns {$CancellablePromise<settings$0.Settings>}
 */
export function UpdateStorageSettings(input, expectedRevision) {
    return $Call.ByID(3724926201, input, expectedRevision).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {settings$0.TerminalSettings} input
 * @param {number} expectedRevision
 * @returns {$CancellablePromise<settings$0.Settings>}
 */
export function UpdateTerminalSettings(input, expectedRevision) {
    return $Call.ByID(2545734590, input, expectedRevision).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

// Private type creation functions
const $$createType0 = desktop$0.RuntimeInfo.createFrom;
const $$createType1 = desktop$0.CleanupResult.createFrom;
const $$createType2 = desktop$0.DiagnosticsExport.createFrom;
const $$createType3 = settings$0.Settings.createFrom;
const $$createType4 = desktop$0.StorageUsage.createFrom;
const $$createType5 = agentrun$0.ClaudeConfiguration.createFrom;
const $$createType6 = agentrun$0.CodexConfiguration.createFrom;
const $$createType7 = agentrun$0.HarnessConfiguration.createFrom;
const $$createType8 = desktop$0.CleanupPreview.createFrom;
