// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as desktop$0 from "../../service/desktop/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as skillmanager$0 from "../../service/skillmanager/models.js";

/**
 * @param {skillmanager$0.AddTargetInput} input
 * @returns {$CancellablePromise<skillmanager$0.SyncTarget>}
 */
export function AddSyncTarget(input) {
    return $Call.ByID(65831119, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {skillmanager$0.SaveSkillInput} input
 * @returns {$CancellablePromise<skillmanager$0.SkillDocument>}
 */
export function CreateSkill(input) {
    return $Call.ByID(90115767, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {desktop$0.SkillDebugInput} input
 * @returns {$CancellablePromise<desktop$0.SkillDebugResult>}
 */
export function Debug(input) {
    return $Call.ByID(2287426605, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DeleteSkill(name) {
    return $Call.ByID(640365398, name);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<skillmanager$0.SkillDocument>}
 */
export function GetSkill(name) {
    return $Call.ByID(1715022415, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<skillmanager$0.Skill[]>}
 */
export function ListSkills() {
    return $Call.ByID(3797723156).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function RemoveSyncTarget(id) {
    return $Call.ByID(3559332128, id);
}

/**
 * @returns {$CancellablePromise<skillmanager$0.SyncTarget[]>}
 */
export function ScanSyncTargets() {
    return $Call.ByID(2545266950).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<skillmanager$0.SyncResult>}
 */
export function Sync(id) {
    return $Call.ByID(3220724177, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {skillmanager$0.SaveSkillInput} input
 * @returns {$CancellablePromise<skillmanager$0.SkillDocument>}
 */
export function UpdateSkill(input) {
    return $Call.ByID(1157215936, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = skillmanager$0.SyncTarget.createFrom;
const $$createType1 = skillmanager$0.SkillDocument.createFrom;
const $$createType2 = desktop$0.SkillDebugResult.createFrom;
const $$createType3 = skillmanager$0.Skill.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Array($$createType0);
const $$createType6 = skillmanager$0.SyncResult.createFrom;
