// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tasks$0 from "../../domain/tasks/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as workflows$0 from "../../domain/workflows/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as desktop$0 from "../../service/desktop/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as runstream$0 from "../../service/desktop/runstream/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as workflows$1 from "../../usecase/workflows/models.js";

/**
 * @param {string} runID
 * @returns {$CancellablePromise<workflows$0.Run>}
 */
export function CancelRun(runID) {
    return $Call.ByID(1714304680, runID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {desktop$0.CreateTaskInput} input
 * @returns {$CancellablePromise<tasks$0.Task>}
 */
export function CreateTask(input) {
    return $Call.ByID(2719115984, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} taskID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteTask(taskID) {
    return $Call.ByID(3834834523, taskID);
}

/**
 * @param {string} runID
 * @param {desktop$0.InstructionInput} input
 * @returns {$CancellablePromise<workflows$0.Instruction>}
 */
export function EnqueueInstruction(runID, input) {
    return $Call.ByID(4268144915, runID, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} taskID
 * @param {string} confirmationToken
 * @returns {$CancellablePromise<tasks$0.Task>}
 */
export function EnqueueTask(taskID, confirmationToken) {
    return $Call.ByID(730833856, taskID, confirmationToken).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} runID
 * @returns {$CancellablePromise<desktop$0.RunDetail>}
 */
export function GetRun(runID) {
    return $Call.ByID(700987492, runID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} runID
 * @returns {$CancellablePromise<runstream$0.Frame[]>}
 */
export function GetRunStreamSnapshot(runID) {
    return $Call.ByID(2473884600, runID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} runID
 * @returns {$CancellablePromise<desktop$0.RuntimeEventView[]>}
 */
export function GetRunTranscript(runID) {
    return $Call.ByID(1244916286, runID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {string} runID
 * @param {desktop$0.InstructionInput} input
 * @returns {$CancellablePromise<workflows$0.Instruction>}
 */
export function InterruptAndInsert(runID, input) {
    return $Call.ByID(3458601712, runID, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} runID
 * @returns {$CancellablePromise<workflows$0.Run>}
 */
export function InterruptRun(runID) {
    return $Call.ByID(292099625, runID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} runID
 * @param {number} afterSeq
 * @returns {$CancellablePromise<desktop$0.WorkflowEventView[]>}
 */
export function ListRunEvents(runID, afterSeq) {
    return $Call.ByID(2042597943, runID, afterSeq).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @param {desktop$0.ListRunsInput} input
 * @returns {$CancellablePromise<desktop$0.RunListPage>}
 */
export function ListRuns(input) {
    return $Call.ByID(768937475, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * @param {string} taskID
 * @returns {$CancellablePromise<workflows$0.Run[]>}
 */
export function ListRunsByTask(taskID) {
    return $Call.ByID(413122787, taskID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * @param {string} workspaceID
 * @returns {$CancellablePromise<tasks$0.Task[]>}
 */
export function ListTasks(workspaceID) {
    return $Call.ByID(3566902885, workspaceID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * @param {string} taskID
 * @returns {$CancellablePromise<desktop$0.RunStartPreview>}
 */
export function PreviewRun(taskID) {
    return $Call.ByID(864427724, taskID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * @param {string} runID
 * @param {desktop$0.InstructionInput} input
 * @returns {$CancellablePromise<workflows$0.Instruction>}
 */
export function QueueFollowUp(runID, input) {
    return $Call.ByID(3173446428, runID, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} workspaceID
 * @returns {$CancellablePromise<tasks$0.Task[]>}
 */
export function QueueSnapshot(workspaceID) {
    return $Call.ByID(1492889848, workspaceID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * @param {string} runID
 * @param {string} instructionID
 * @returns {$CancellablePromise<void>}
 */
export function RemoveInstruction(runID, instructionID) {
    return $Call.ByID(1562733667, runID, instructionID);
}

/**
 * @param {string} taskID
 * @param {string} title
 * @returns {$CancellablePromise<tasks$0.Task>}
 */
export function RenameTask(taskID, title) {
    return $Call.ByID(4111900838, taskID, title).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {desktop$0.PermissionDecisionInput} input
 * @returns {$CancellablePromise<void>}
 */
export function RespondPermission(input) {
    return $Call.ByID(2953322829, input);
}

/**
 * @param {string} runID
 * @param {string} instruction
 * @returns {$CancellablePromise<workflows$0.Run>}
 */
export function ResumeRun(runID, instruction) {
    return $Call.ByID(1628819071, runID, instruction).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} runID
 * @param {desktop$0.ResumeRunInput} input
 * @returns {$CancellablePromise<workflows$0.Run>}
 */
export function ResumeRunConfigured(runID, input) {
    return $Call.ByID(1746256047, runID, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {desktop$0.SearchTasksInput} input
 * @returns {$CancellablePromise<desktop$0.TaskSearchPage>}
 */
export function SearchTasks(input) {
    return $Call.ByID(3760506421, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * @param {string} taskID
 * @param {boolean} pinned
 * @returns {$CancellablePromise<tasks$0.Task>}
 */
export function SetTaskPinned(taskID, pinned) {
    return $Call.ByID(1072326008, taskID, pinned).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} taskID
 * @param {string} confirmationToken
 * @returns {$CancellablePromise<workflows$0.Run>}
 */
export function StartRun(taskID, confirmationToken) {
    return $Call.ByID(2093366980, taskID, confirmationToken).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} runID
 * @param {string} instructionID
 * @returns {$CancellablePromise<workflows$0.Instruction>}
 */
export function SteerInstruction(runID, instructionID) {
    return $Call.ByID(1909385582, runID, instructionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

// Private type creation functions
const $$createType0 = workflows$0.Run.createFrom;
const $$createType1 = tasks$0.Task.createFrom;
const $$createType2 = workflows$0.Instruction.createFrom;
const $$createType3 = desktop$0.RunDetail.createFrom;
const $$createType4 = workflows$1.RuntimeEventFrame.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = desktop$0.RuntimeEventView.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = desktop$0.WorkflowEventView.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = desktop$0.RunListPage.createFrom;
const $$createType11 = $Create.Array($$createType0);
const $$createType12 = $Create.Array($$createType1);
const $$createType13 = desktop$0.RunStartPreview.createFrom;
const $$createType14 = desktop$0.TaskSearchPage.createFrom;
