// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WindowBinding exposes the small piece of native window management that the
 * web UI needs. The actual windows are owned by the desktop package; keeping
 * callbacks here avoids coupling the transport layer to a particular window
 * layout or platform implementation.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @returns {$CancellablePromise<void>}
 */
export function CloseInspector() {
    return $Call.ByID(956610578);
}

/**
 * OpenInspector detaches the run inspector into its own window so it can live
 * on a second display. CloseInspector puts it back in the main workbench.
 * @returns {$CancellablePromise<void>}
 */
export function OpenInspector() {
    return $Call.ByID(2908288200);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function OpenSettings() {
    return $Call.ByID(2874510250);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function OpenWorkflows() {
    return $Call.ByID(3483995735);
}
