// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as workspaces$0 from "../../domain/workspaces/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as desktop$0 from "../../service/desktop/models.js";

/**
 * @param {desktop$0.AddWorkspaceInput} input
 * @returns {$CancellablePromise<workspaces$0.Workspace>}
 */
export function AddWorkspace(input) {
    return $Call.ByID(4152638586, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function ChooseAttachments() {
    return $Call.ByID(3384592839).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function ChooseDirectory() {
    return $Call.ByID(80681666);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<workspaces$0.Workspace>}
 */
export function GetWorkspace(id) {
    return $Call.ByID(1390246223, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<desktop$0.WorkspaceStatus>}
 */
export function GetWorkspaceStatus(id) {
    return $Call.ByID(57993081, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} workspaceID
 * @param {string} directory
 * @returns {$CancellablePromise<desktop$0.WorkspaceFileEntry[]>}
 */
export function ListWorkspaceFiles(workspaceID, directory) {
    return $Call.ByID(3025621542, workspaceID, directory).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<workspaces$0.Workspace[]>}
 */
export function ListWorkspaces() {
    return $Call.ByID(2383037796).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<workspaces$0.Workspace>}
 */
export function OpenWorkspace(id) {
    return $Call.ByID(538828779, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} workspaceID
 * @param {string} path
 * @returns {$CancellablePromise<desktop$0.WorkspaceFileDocument>}
 */
export function ReadWorkspaceFile(workspaceID, path) {
    return $Call.ByID(2305632485, workspaceID, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function RemoveWorkspace(id) {
    return $Call.ByID(1769621719, id);
}

/**
 * @param {string} id
 * @param {boolean} pinned
 * @returns {$CancellablePromise<workspaces$0.Workspace>}
 */
export function SetWorkspacePinned(id, pinned) {
    return $Call.ByID(4111845597, id, pinned).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {desktop$0.UpdateWorkspaceInput} input
 * @returns {$CancellablePromise<workspaces$0.Workspace>}
 */
export function UpdateWorkspace(input) {
    return $Call.ByID(1645047680, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {desktop$0.WriteWorkspaceFileInput} input
 * @returns {$CancellablePromise<desktop$0.WorkspaceFileDocument>}
 */
export function WriteWorkspaceFile(input) {
    return $Call.ByID(2020849016, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

// Private type creation functions
const $$createType0 = workspaces$0.Workspace.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = desktop$0.WorkspaceStatus.createFrom;
const $$createType3 = desktop$0.WorkspaceFileEntry.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Array($$createType0);
const $$createType6 = desktop$0.WorkspaceFileDocument.createFrom;
