// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as terminal$0 from "../../service/terminal/models.js";

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function CloseTerminal(sessionID) {
    return $Call.ByID(3528885996, sessionID);
}

/**
 * @param {terminal$0.CreateInput} input
 * @returns {$CancellablePromise<terminal$0.Session>}
 */
export function CreateTerminal(input) {
    return $Call.ByID(1146900124, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<terminal$0.Session[]>}
 */
export function ListTerminals() {
    return $Call.ByID(1965288193).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} sessionID
 * @param {number} rows
 * @param {number} cols
 * @returns {$CancellablePromise<void>}
 */
export function ResizeTerminal(sessionID, rows, cols) {
    return $Call.ByID(4075997816, sessionID, rows, cols);
}

/**
 * @param {string} sessionID
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function WriteTerminal(sessionID, data) {
    return $Call.ByID(1964404923, sessionID, data);
}

// Private type creation functions
const $$createType0 = terminal$0.Session.createFrom;
const $$createType1 = $Create.Array($$createType0);
