// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as desktop$0 from "../../service/desktop/models.js";

/**
 * @param {string} requestID
 * @returns {$CancellablePromise<void>}
 */
export function Cancel(requestID) {
    return $Call.ByID(699510945, requestID);
}

/**
 * @param {desktop$0.WhiteboardProposalInput} input
 * @returns {$CancellablePromise<desktop$0.WhiteboardProposal>}
 */
export function ProposeChanges(input) {
    return $Call.ByID(232958860, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = desktop$0.WhiteboardProposal.createFrom;
