// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WindowBinding exposes the small piece of native window management that the
 * web UI needs. The actual windows are owned by the desktop package; keeping
 * callbacks here avoids coupling the transport layer to a particular window
 * layout or platform implementation.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @returns {$CancellablePromise<void>}
 */
export function OpenSettings() {
    return $Call.ByID(1696843073);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function OpenWorkflows() {
    return $Call.ByID(2572810030);
}
