// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as workspaces$0 from "../../domain/workspaces/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as desktop$0 from "../../service/desktop/models.js";

/**
 * @param {desktop$0.AddWorkspaceInput} input
 * @returns {$CancellablePromise<workspaces$0.Workspace>}
 */
export function AddWorkspace(input) {
    return $Call.ByID(3681900251, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function ChooseAttachments() {
    return $Call.ByID(2255764812).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function ChooseDirectory() {
    return $Call.ByID(1379470121);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<workspaces$0.Workspace>}
 */
export function GetWorkspace(id) {
    return $Call.ByID(1986993754, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<desktop$0.WorkspaceStatus>}
 */
export function GetWorkspaceStatus(id) {
    return $Call.ByID(2337999140, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<workspaces$0.Workspace[]>}
 */
export function ListWorkspaces() {
    return $Call.ByID(117281613).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<workspaces$0.Workspace>}
 */
export function OpenWorkspace(id) {
    return $Call.ByID(2917761272, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function RemoveWorkspace(id) {
    return $Call.ByID(1963398616, id);
}

/**
 * @param {string} id
 * @param {boolean} pinned
 * @returns {$CancellablePromise<workspaces$0.Workspace>}
 */
export function SetWorkspacePinned(id, pinned) {
    return $Call.ByID(1864814896, id, pinned).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = workspaces$0.Workspace.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = desktop$0.WorkspaceStatus.createFrom;
const $$createType3 = $Create.Array($$createType0);
