// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agentrun$0 from "../agentrun/models.js";

/**
 * RuntimeEventFrame is the transport-neutral event emitted while a workflow
 * step is running. Service and transport layers decide how to deliver it.
 */
export class RuntimeEventFrame {
    /**
     * Creates a new RuntimeEventFrame instance.
     * @param {Partial<RuntimeEventFrame>} [$$source = {}] - The source object to create the RuntimeEventFrame.
     */
    constructor($$source = {}) {
        if (!("runId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["runId"] = "";
        }
        if (!("stepRunId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["stepRunId"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["seq"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Attachments holds managed file paths on a user follow-up.
             * @member
             * @type {string[] | undefined}
             */
            this["attachments"] = undefined;
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {agentrun$0.EventKind}
             */
            this["kind"] = agentrun$0.EventKind.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * Usage is the latest cumulative token accounting for this step. Runtimes
             * that report usage before completion attach it to KindUsage so the desktop
             * can update its metrics while the agent is still running.
             * @member
             * @type {agentrun$0.Usage | null | undefined}
             */
            this["usage"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * StreamID is stable for all chunks belonging to one logical message,
             * reasoning block, or tool output. Empty identifies an atomic event.
             * @member
             * @type {string | undefined}
             */
            this["streamId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Phase controls whether Text starts, appends to, replaces, or completes a
             * logical stream. Revision is assigned by the orchestration collector after
             * it batches provider token deltas.
             * @member
             * @type {agentrun$0.StreamPhase | undefined}
             */
            this["phase"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["revision"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Text is the human-meaningful payload: message prose, command, file path,
             * or error description, depending on Kind.
             * @member
             * @type {string | undefined}
             */
            this["text"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Raw is the original JSONL line from the runtime, retained for debugging
             * and forward compatibility with fields we do not yet model.
             * @member
             * @type {string | undefined}
             */
            this["raw"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Failed reports that this individual event is an error: a tool that
             * returned an error, not a run that ended badly. A step can fail while most
             * of its tool calls succeeded, so callers must not infer one from the other.
             * @member
             * @type {boolean | undefined}
             */
            this["failed"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Context is the context-window occupancy observed at this step, attached
             * to KindUsage beside Usage. It is a separate field precisely because it
             * is not a subset of Usage — see [ContextUsage].
             * @member
             * @type {agentrun$0.ContextUsage | null | undefined}
             */
            this["context"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Permission is populated for permission_request and permission_resolved
             * events. PermissionDecision is "allow" or "deny" on the resolved event.
             * @member
             * @type {agentrun$0.PermissionRequest | null | undefined}
             */
            this["permission"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["permissionDecision"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * UserInput is populated for user_input_request and user_input_resolved;
             * UserInputResponse is populated only after the host answers or dismisses.
             * @member
             * @type {agentrun$0.UserInputRequest | null | undefined}
             */
            this["userInput"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {agentrun$0.UserInputResponse | null | undefined}
             */
            this["userInputResponse"] = undefined;
        }
        if (!("at" in $$source)) {
            /**
             * At is when the engine observed the event.
             * @member
             * @type {string}
             */
            this["at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuntimeEventFrame instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RuntimeEventFrame}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        const $$createField5_0 = $$createType2;
        const $$createField12_0 = $$createType4;
        const $$createField13_0 = $$createType6;
        const $$createField15_0 = $$createType8;
        const $$createField16_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("attachments" in $$parsedSource) {
            $$parsedSource["attachments"] = $$createField3_0($$parsedSource["attachments"]);
        }
        if ("usage" in $$parsedSource) {
            $$parsedSource["usage"] = $$createField5_0($$parsedSource["usage"]);
        }
        if ("context" in $$parsedSource) {
            $$parsedSource["context"] = $$createField12_0($$parsedSource["context"]);
        }
        if ("permission" in $$parsedSource) {
            $$parsedSource["permission"] = $$createField13_0($$parsedSource["permission"]);
        }
        if ("userInput" in $$parsedSource) {
            $$parsedSource["userInput"] = $$createField15_0($$parsedSource["userInput"]);
        }
        if ("userInputResponse" in $$parsedSource) {
            $$parsedSource["userInputResponse"] = $$createField16_0($$parsedSource["userInputResponse"]);
        }
        return new RuntimeEventFrame(/** @type {Partial<RuntimeEventFrame>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = agentrun$0.Usage.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = agentrun$0.ContextUsage.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = agentrun$0.PermissionRequest.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = agentrun$0.UserInputRequest.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = agentrun$0.UserInputResponse.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
