// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as workspaces$0 from "../../domain/workspaces/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agentrun$0 from "../../usecase/agentrun/models.js";

export class Health {
    /**
     * Creates a new Health instance.
     * @param {Partial<Health>} [$$source = {}] - The source object to create the Health.
     */
    constructor($$source = {}) {
        if (!("workerId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["workerId"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("protocolVersion" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["protocolVersion"] = 0;
        }
        if (!("runtimes" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: boolean }}
             */
            this["runtimes"] = {};
        }
        if (!("capabilities" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: boolean }}
             */
            this["capabilities"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Health instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Health}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("runtimes" in $$parsedSource) {
            $$parsedSource["runtimes"] = $$createField3_0($$parsedSource["runtimes"]);
        }
        if ("capabilities" in $$parsedSource) {
            $$parsedSource["capabilities"] = $$createField4_0($$parsedSource["capabilities"]);
        }
        return new Health(/** @type {Partial<Health>} */($$parsedSource));
    }
}

export class Info {
    /**
     * Creates a new Info instance.
     * @param {Partial<Info>} [$$source = {}] - The source object to create the Info.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("baseUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["baseUrl"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["caFile"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["clientCertFile"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["clientKeyFile"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["serverName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["serverCertificateSha256"] = undefined;
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("hasToken" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasToken"] = false;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updatedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Info instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Info}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Info(/** @type {Partial<Info>} */($$parsedSource));
    }
}

/**
 * SharedRun is a projection of the host's durable task record. Clients cache
 * it for offline viewing; only the host owns execution and history.
 */
export class SharedRun {
    /**
     * Creates a new SharedRun instance.
     * @param {Partial<SharedRun>} [$$source = {}] - The source object to create the SharedRun.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("conversationId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["conversationId"] = "";
        }
        if (!("workerId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["workerId"] = "";
        }
        if (!("workspaceId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["workspaceId"] = "";
        }
        if (!("runtime" in $$source)) {
            /**
             * @member
             * @type {agentrun$0.Runtime}
             */
            this["runtime"] = agentrun$0.Runtime.$zero;
        }
        if (!("prompt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["prompt"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["title"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["turnCount"] = undefined;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["shared"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {agentrun$0.Event[] | undefined}
             */
            this["events"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {agentrun$0.Result | null | undefined}
             */
            this["result"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (!("startedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["startedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["finishedAt"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SharedRun instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SharedRun}
     */
    static createFrom($$source = {}) {
        const $$createField10_0 = $$createType2;
        const $$createField11_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("events" in $$parsedSource) {
            $$parsedSource["events"] = $$createField10_0($$parsedSource["events"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField11_0($$parsedSource["result"]);
        }
        return new SharedRun(/** @type {Partial<SharedRun>} */($$parsedSource));
    }
}

export class UpdateInput {
    /**
     * Creates a new UpdateInput instance.
     * @param {Partial<UpdateInput>} [$$source = {}] - The source object to create the UpdateInput.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("baseUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["baseUrl"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["caFile"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["clientCertFile"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["clientKeyFile"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["serverName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["serverCertificateSha256"] = undefined;
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInput(/** @type {Partial<UpdateInput>} */($$parsedSource));
    }
}

export class WorkspaceMapping {
    /**
     * Creates a new WorkspaceMapping instance.
     * @param {Partial<WorkspaceMapping>} [$$source = {}] - The source object to create the WorkspaceMapping.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["name"] = undefined;
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["remoteUrl"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["revision"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["managed"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Shared marks a mapping this worker serves but does not own — a project
             * the desktop hosting it already had. The phone can run against it; only
             * the desktop can change or remove it.
             * @member
             * @type {boolean | undefined}
             */
            this["shared"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * RemoteHost names the machine a shared Remote FS project lives on, so the
             * phone can tell a project on the desktop from one the desktop reaches over
             * SSH. Empty for anything on the worker's own disk.
             * @member
             * @type {string | undefined}
             */
            this["remoteHost"] = undefined;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updatedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceMapping instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WorkspaceMapping}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceMapping(/** @type {Partial<WorkspaceMapping>} */($$parsedSource));
    }
}

export class WorkspacePrepareRequest {
    /**
     * Creates a new WorkspacePrepareRequest instance.
     * @param {Partial<WorkspacePrepareRequest>} [$$source = {}] - The source object to create the WorkspacePrepareRequest.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["name"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["path"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["remoteUrl"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["revision"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspacePrepareRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WorkspacePrepareRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspacePrepareRequest(/** @type {Partial<WorkspacePrepareRequest>} */($$parsedSource));
    }
}

export class WorkspacePrepareResult {
    /**
     * Creates a new WorkspacePrepareResult instance.
     * @param {Partial<WorkspacePrepareResult>} [$$source = {}] - The source object to create the WorkspacePrepareResult.
     */
    constructor($$source = {}) {
        if (!("mapping" in $$source)) {
            /**
             * @member
             * @type {WorkspaceMapping}
             */
            this["mapping"] = (new WorkspaceMapping());
        }
        if (!("git" in $$source)) {
            /**
             * @member
             * @type {workspaces$0.GitSnapshot}
             */
            this["git"] = (new workspaces$0.GitSnapshot());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspacePrepareResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WorkspacePrepareResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType5;
        const $$createField1_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("mapping" in $$parsedSource) {
            $$parsedSource["mapping"] = $$createField0_0($$parsedSource["mapping"]);
        }
        if ("git" in $$parsedSource) {
            $$parsedSource["git"] = $$createField1_0($$parsedSource["git"]);
        }
        return new WorkspacePrepareResult(/** @type {Partial<WorkspacePrepareResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = agentrun$0.Event.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = agentrun$0.Result.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = WorkspaceMapping.createFrom;
const $$createType6 = workspaces$0.GitSnapshot.createFrom;
