// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as workspaces$0 from "../../domain/workspaces/models.js";

export class Health {
    /**
     * Creates a new Health instance.
     * @param {Partial<Health>} [$$source = {}] - The source object to create the Health.
     */
    constructor($$source = {}) {
        if (!("workerId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["workerId"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("protocolVersion" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["protocolVersion"] = 0;
        }
        if (!("runtimes" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: boolean }}
             */
            this["runtimes"] = {};
        }
        if (!("capabilities" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: boolean }}
             */
            this["capabilities"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Health instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Health}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("runtimes" in $$parsedSource) {
            $$parsedSource["runtimes"] = $$createField3_0($$parsedSource["runtimes"]);
        }
        if ("capabilities" in $$parsedSource) {
            $$parsedSource["capabilities"] = $$createField4_0($$parsedSource["capabilities"]);
        }
        return new Health(/** @type {Partial<Health>} */($$parsedSource));
    }
}

export class Info {
    /**
     * Creates a new Info instance.
     * @param {Partial<Info>} [$$source = {}] - The source object to create the Info.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("baseUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["baseUrl"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["caFile"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["clientCertFile"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["clientKeyFile"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["serverName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["serverCertificateSha256"] = undefined;
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("hasToken" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasToken"] = false;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updatedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Info instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Info}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Info(/** @type {Partial<Info>} */($$parsedSource));
    }
}

export class UpdateInput {
    /**
     * Creates a new UpdateInput instance.
     * @param {Partial<UpdateInput>} [$$source = {}] - The source object to create the UpdateInput.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("baseUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["baseUrl"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["caFile"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["clientCertFile"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["clientKeyFile"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["serverName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["serverCertificateSha256"] = undefined;
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInput(/** @type {Partial<UpdateInput>} */($$parsedSource));
    }
}

export class WorkspaceMapping {
    /**
     * Creates a new WorkspaceMapping instance.
     * @param {Partial<WorkspaceMapping>} [$$source = {}] - The source object to create the WorkspaceMapping.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["name"] = undefined;
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["remoteUrl"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["revision"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["managed"] = undefined;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updatedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceMapping instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WorkspaceMapping}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceMapping(/** @type {Partial<WorkspaceMapping>} */($$parsedSource));
    }
}

export class WorkspacePrepareRequest {
    /**
     * Creates a new WorkspacePrepareRequest instance.
     * @param {Partial<WorkspacePrepareRequest>} [$$source = {}] - The source object to create the WorkspacePrepareRequest.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["name"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["path"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["remoteUrl"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["revision"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspacePrepareRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WorkspacePrepareRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspacePrepareRequest(/** @type {Partial<WorkspacePrepareRequest>} */($$parsedSource));
    }
}

export class WorkspacePrepareResult {
    /**
     * Creates a new WorkspacePrepareResult instance.
     * @param {Partial<WorkspacePrepareResult>} [$$source = {}] - The source object to create the WorkspacePrepareResult.
     */
    constructor($$source = {}) {
        if (!("mapping" in $$source)) {
            /**
             * @member
             * @type {WorkspaceMapping}
             */
            this["mapping"] = (new WorkspaceMapping());
        }
        if (!("git" in $$source)) {
            /**
             * @member
             * @type {workspaces$0.GitSnapshot}
             */
            this["git"] = (new workspaces$0.GitSnapshot());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspacePrepareResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WorkspacePrepareResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("mapping" in $$parsedSource) {
            $$parsedSource["mapping"] = $$createField0_0($$parsedSource["mapping"]);
        }
        if ("git" in $$parsedSource) {
            $$parsedSource["git"] = $$createField1_0($$parsedSource["git"]);
        }
        return new WorkspacePrepareResult(/** @type {Partial<WorkspacePrepareResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = WorkspaceMapping.createFrom;
const $$createType2 = workspaces$0.GitSnapshot.createFrom;
