// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AddTargetInput {
    /**
     * Creates a new AddTargetInput instance.
     * @param {Partial<AddTargetInput>} [$$source = {}] - The source object to create the AddTargetInput.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AddTargetInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AddTargetInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AddTargetInput(/** @type {Partial<AddTargetInput>} */($$parsedSource));
    }
}

/**
 * SaveSkillFileInput is a single-argument shape so the generated Wails binding
 * keeps a stable signature as the editor grows.
 */
export class SaveSkillFileInput {
    /**
     * Creates a new SaveSkillFileInput instance.
     * @param {Partial<SaveSkillFileInput>} [$$source = {}] - The source object to create the SaveSkillFileInput.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveSkillFileInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SaveSkillFileInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SaveSkillFileInput(/** @type {Partial<SaveSkillFileInput>} */($$parsedSource));
    }
}

export class SaveSkillInput {
    /**
     * Creates a new SaveSkillInput instance.
     * @param {Partial<SaveSkillInput>} [$$source = {}] - The source object to create the SaveSkillInput.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveSkillInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SaveSkillInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SaveSkillInput(/** @type {Partial<SaveSkillInput>} */($$parsedSource));
    }
}

/**
 * SetTargetSkillsInput narrows what a target receives. An empty list means the
 * whole library, which is what every target did before selection existed and
 * what a newly added target still does.
 */
export class SetTargetSkillsInput {
    /**
     * Creates a new SetTargetSkillsInput instance.
     * @param {Partial<SetTargetSkillsInput>} [$$source = {}] - The source object to create the SetTargetSkillsInput.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("skills" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["skills"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SetTargetSkillsInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SetTargetSkillsInput}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("skills" in $$parsedSource) {
            $$parsedSource["skills"] = $$createField1_0($$parsedSource["skills"]);
        }
        return new SetTargetSkillsInput(/** @type {Partial<SetTargetSkillsInput>} */($$parsedSource));
    }
}

/**
 * Skill is the lightweight list representation of one directory-backed skill.
 */
export class Skill {
    /**
     * Creates a new Skill instance.
     * @param {Partial<Skill>} [$$source = {}] - The source object to create the Skill.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("sizeBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sizeBytes"] = 0;
        }
        if (!("digest" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["digest"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Skill instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Skill}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Skill(/** @type {Partial<Skill>} */($$parsedSource));
    }
}

/**
 * SkillDocument includes the editable SKILL.md source.
 */
export class SkillDocument {
    /**
     * Creates a new SkillDocument instance.
     * @param {Partial<SkillDocument>} [$$source = {}] - The source object to create the SkillDocument.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("sizeBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sizeBytes"] = 0;
        }
        if (!("digest" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["digest"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillDocument instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SkillDocument}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SkillDocument(/** @type {Partial<SkillDocument>} */($$parsedSource));
    }
}

/**
 * SkillFileContent is one editable text file inside the managed Skills root.
 * It is how the Skills inspector reads and writes the resources that sit
 * beside SKILL.md — references, scripts, prompts — without handing the UI a
 * general-purpose filesystem.
 */
export class SkillFileContent {
    /**
     * Creates a new SkillFileContent instance.
     * @param {Partial<SkillFileContent>} [$$source = {}] - The source object to create the SkillFileContent.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("sizeBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sizeBytes"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["modifiedAt"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillFileContent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SkillFileContent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SkillFileContent(/** @type {Partial<SkillFileContent>} */($$parsedSource));
    }
}

/**
 * SkillFileEntry is one direct child of a directory inside the managed Skills
 * root. Paths are always relative to ~/.onecatch/skills and symlinks are never
 * followed or returned.
 */
export class SkillFileEntry {
    /**
     * Creates a new SkillFileEntry instance.
     * @param {Partial<SkillFileEntry>} [$$source = {}] - The source object to create the SkillFileEntry.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("directory" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["directory"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["size"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["modifiedAt"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillFileEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SkillFileEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SkillFileEntry(/** @type {Partial<SkillFileEntry>} */($$parsedSource));
    }
}

export class SyncResult {
    /**
     * Creates a new SyncResult instance.
     * @param {Partial<SyncResult>} [$$source = {}] - The source object to create the SyncResult.
     */
    constructor($$source = {}) {
        if (!("target" in $$source)) {
            /**
             * @member
             * @type {SyncTarget}
             */
            this["target"] = (new SyncTarget());
        }
        if (!("syncedSkills" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["syncedSkills"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["output"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SyncResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("target" in $$parsedSource) {
            $$parsedSource["target"] = $$createField0_0($$parsedSource["target"]);
        }
        return new SyncResult(/** @type {Partial<SyncResult>} */($$parsedSource));
    }
}

/**
 * SyncSkillResult reports one skill pushed to every target that receives it.
 */
export class SyncSkillResult {
    /**
     * Creates a new SyncSkillResult instance.
     * @param {Partial<SyncSkillResult>} [$$source = {}] - The source object to create the SyncSkillResult.
     */
    constructor($$source = {}) {
        if (!("skill" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["skill"] = "";
        }
        if (!("targets" in $$source)) {
            /**
             * @member
             * @type {SyncTarget[]}
             */
            this["targets"] = [];
        }
        if (!("synced" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["synced"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["output"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncSkillResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SyncSkillResult}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("targets" in $$parsedSource) {
            $$parsedSource["targets"] = $$createField1_0($$parsedSource["targets"]);
        }
        return new SyncSkillResult(/** @type {Partial<SyncSkillResult>} */($$parsedSource));
    }
}

/**
 * SyncTarget is a scanned external Agent Skills directory.
 */
export class SyncTarget {
    /**
     * Creates a new SyncTarget instance.
     * @param {Partial<SyncTarget>} [$$source = {}] - The source object to create the SyncTarget.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("builtin" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["builtin"] = false;
        }
        if (!("exists" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["exists"] = false;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("syncedSkills" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["syncedSkills"] = 0;
        }
        if (!("totalSkills" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalSkills"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["lastSyncedAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastError"] = undefined;
        }
        if (!("rsyncAvailable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["rsyncAvailable"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * Skills is the configured subset this target receives. Empty means the
             * whole library; TotalSkills already counts only what will be sent, so the
             * two together say both "3 of 5 chosen" and "2 of those 3 are current".
             * @member
             * @type {string[] | undefined}
             */
            this["skills"] = undefined;
        }
        if (!("librarySkills" in $$source)) {
            /**
             * LibrarySkills is the size of the whole library, so a partial selection
             * can be described without a second call.
             * @member
             * @type {number}
             */
            this["librarySkills"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * SyncedNames are the selected skills whose copy at the target matches the
             * library byte for byte. Naming them, rather than only counting them, is
             * what lets a per-skill view say which of its targets are behind.
             * @member
             * @type {string[] | undefined}
             */
            this["syncedNames"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncTarget instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SyncTarget}
     */
    static createFrom($$source = {}) {
        const $$createField11_0 = $$createType0;
        const $$createField13_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("skills" in $$parsedSource) {
            $$parsedSource["skills"] = $$createField11_0($$parsedSource["skills"]);
        }
        if ("syncedNames" in $$parsedSource) {
            $$parsedSource["syncedNames"] = $$createField13_0($$parsedSource["syncedNames"]);
        }
        return new SyncTarget(/** @type {Partial<SyncTarget>} */($$parsedSource));
    }
}

/**
 * UpdateTargetInput repoints an existing target. A built-in target keeps its
 * name — only the directory is the user's to choose, which is how Settings
 * points Codex or Claude Code at a non-default install.
 */
export class UpdateTargetInput {
    /**
     * Creates a new UpdateTargetInput instance.
     * @param {Partial<UpdateTargetInput>} [$$source = {}] - The source object to create the UpdateTargetInput.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["name"] = undefined;
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateTargetInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateTargetInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateTargetInput(/** @type {Partial<UpdateTargetInput>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = SyncTarget.createFrom;
const $$createType2 = $Create.Array($$createType1);
