// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AddTargetInput {
    /**
     * Creates a new AddTargetInput instance.
     * @param {Partial<AddTargetInput>} [$$source = {}] - The source object to create the AddTargetInput.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AddTargetInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AddTargetInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AddTargetInput(/** @type {Partial<AddTargetInput>} */($$parsedSource));
    }
}

export class SaveSkillInput {
    /**
     * Creates a new SaveSkillInput instance.
     * @param {Partial<SaveSkillInput>} [$$source = {}] - The source object to create the SaveSkillInput.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveSkillInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SaveSkillInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SaveSkillInput(/** @type {Partial<SaveSkillInput>} */($$parsedSource));
    }
}

/**
 * Skill is the lightweight list representation of one directory-backed skill.
 */
export class Skill {
    /**
     * Creates a new Skill instance.
     * @param {Partial<Skill>} [$$source = {}] - The source object to create the Skill.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("sizeBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sizeBytes"] = 0;
        }
        if (!("digest" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["digest"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Skill instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Skill}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Skill(/** @type {Partial<Skill>} */($$parsedSource));
    }
}

/**
 * SkillDocument includes the editable SKILL.md source.
 */
export class SkillDocument {
    /**
     * Creates a new SkillDocument instance.
     * @param {Partial<SkillDocument>} [$$source = {}] - The source object to create the SkillDocument.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("sizeBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sizeBytes"] = 0;
        }
        if (!("digest" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["digest"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillDocument instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SkillDocument}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SkillDocument(/** @type {Partial<SkillDocument>} */($$parsedSource));
    }
}

export class SyncResult {
    /**
     * Creates a new SyncResult instance.
     * @param {Partial<SyncResult>} [$$source = {}] - The source object to create the SyncResult.
     */
    constructor($$source = {}) {
        if (!("target" in $$source)) {
            /**
             * @member
             * @type {SyncTarget}
             */
            this["target"] = (new SyncTarget());
        }
        if (!("syncedSkills" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["syncedSkills"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["output"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SyncResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("target" in $$parsedSource) {
            $$parsedSource["target"] = $$createField0_0($$parsedSource["target"]);
        }
        return new SyncResult(/** @type {Partial<SyncResult>} */($$parsedSource));
    }
}

/**
 * SyncTarget is a scanned external Agent Skills directory.
 */
export class SyncTarget {
    /**
     * Creates a new SyncTarget instance.
     * @param {Partial<SyncTarget>} [$$source = {}] - The source object to create the SyncTarget.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("builtin" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["builtin"] = false;
        }
        if (!("exists" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["exists"] = false;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("syncedSkills" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["syncedSkills"] = 0;
        }
        if (!("totalSkills" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalSkills"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["lastSyncedAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastError"] = undefined;
        }
        if (!("rsyncAvailable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["rsyncAvailable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncTarget instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SyncTarget}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncTarget(/** @type {Partial<SyncTarget>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = SyncTarget.createFrom;
