// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as oneshot$0 from "../../../clients/oneshot/models.js";

/**
 * @param {string} agentID
 * @returns {$CancellablePromise<oneshot$0.Agent>}
 */
export function GetAgent(agentID) {
    return $Call.ByID(2023235694, agentID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<oneshot$0.Agent[]>}
 */
export function ListAgents() {
    return $Call.ByID(1585619185).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = oneshot$0.Agent.createFrom;
const $$createType1 = $Create.Array($$createType0);
