// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as oneshot$0 from "../../../clients/oneshot/models.js";

/**
 * @param {string} artifactID
 * @returns {$CancellablePromise<oneshot$0.ArtifactDownload>}
 */
export function DownloadArtifact(artifactID) {
    return $Call.ByID(2595074784, artifactID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} orderID
 * @returns {$CancellablePromise<oneshot$0.Artifact[]>}
 */
export function ListArtifacts(orderID) {
    return $Call.ByID(3305326597, orderID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} artifactID
 * @returns {$CancellablePromise<oneshot$0.ArtifactShare>}
 */
export function ShareArtifact(artifactID) {
    return $Call.ByID(2738103, artifactID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function ShowInFolder(path) {
    return $Call.ByID(1892184272, path);
}

// Private type creation functions
const $$createType0 = oneshot$0.ArtifactDownload.createFrom;
const $$createType1 = oneshot$0.Artifact.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = oneshot$0.ArtifactShare.createFrom;
