// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as oneshot$0 from "../../../clients/oneshot/models.js";

/**
 * @param {string} conversationID
 * @returns {$CancellablePromise<oneshot$0.Conversation>}
 */
export function ConfirmCheckout(conversationID) {
    return $Call.ByID(898386649, conversationID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} conversationID
 * @returns {$CancellablePromise<oneshot$0.Conversation>}
 */
export function GetConversation(conversationID) {
    return $Call.ByID(2273058398, conversationID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} conversationID
 * @param {string} text
 * @returns {$CancellablePromise<oneshot$0.Conversation>}
 */
export function PostMessage(conversationID, text) {
    return $Call.ByID(2763905252, conversationID, text).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} agentID
 * @param {string} workspace
 * @returns {$CancellablePromise<oneshot$0.Conversation>}
 */
export function StartConversation(agentID, workspace) {
    return $Call.ByID(73328826, agentID, workspace).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = oneshot$0.Conversation.createFrom;
