// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as RuntimeBinding from "./runtimebinding.js";
import * as TaskRunBinding from "./taskrunbinding.js";
import * as WorkflowBinding from "./workflowbinding.js";
import * as WorkspaceBinding from "./workspacebinding.js";
export {
    RuntimeBinding,
    TaskRunBinding,
    WorkflowBinding,
    WorkspaceBinding
};
