// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as oneshot$0 from "../../../clients/oneshot/models.js";

/**
 * @param {string} orderID
 * @returns {$CancellablePromise<oneshot$0.Order>}
 */
export function CancelOrder(orderID) {
    return $Call.ByID(228878300, orderID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {oneshot$0.CreateOrderRequest} input
 * @returns {$CancellablePromise<oneshot$0.Order>}
 */
export function CreateOrder(input) {
    return $Call.ByID(3217498594, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} orderID
 * @returns {$CancellablePromise<oneshot$0.Order>}
 */
export function GetOrder(orderID) {
    return $Call.ByID(2865117266, orderID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetOrderRun returns the live agent run log for an order so the desktop can
 * stream the agent's progress into the conversation.
 * @param {string} orderID
 * @returns {$CancellablePromise<oneshot$0.RunLog>}
 */
export function GetOrderRun(orderID) {
    return $Call.ByID(1650226771, orderID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} status
 * @returns {$CancellablePromise<oneshot$0.Order[]>}
 */
export function ListOrders(status) {
    return $Call.ByID(396717011, status).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

// Private type creation functions
const $$createType0 = oneshot$0.Order.createFrom;
const $$createType1 = oneshot$0.RunLog.createFrom;
const $$createType2 = $Create.Array($$createType0);
