// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as localapp$0 from "../../../internal/app/localapp/models.js";

/**
 * @param {string} runtime
 * @returns {$CancellablePromise<localapp$0.RuntimeInfo>}
 */
export function CheckRuntime(runtime) {
    return $Call.ByID(2179786898, runtime).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<localapp$0.RuntimeInfo[]>}
 */
export function ListRuntimes() {
    return $Call.ByID(403332327).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {localapp$0.RuntimeConfigInput} input
 * @returns {$CancellablePromise<localapp$0.RuntimeInfo>}
 */
export function UpdateRuntimeConfig(input) {
    return $Call.ByID(2010407975, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = localapp$0.RuntimeInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
