// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as localapp$0 from "../../../internal/app/localapp/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../../../internal/domain/settings/models.js";

/**
 * @param {localapp$0.RuntimeDraftInput} input
 * @returns {$CancellablePromise<localapp$0.RuntimeInfo>}
 */
export function CheckRuntimeDraft(input) {
    return $Call.ByID(1044612484, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} previewToken
 * @returns {$CancellablePromise<localapp$0.CleanupResult>}
 */
export function ExecuteCleanup(previewToken) {
    return $Call.ByID(3054612752, previewToken).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {localapp$0.DiagnosticsExportInput} input
 * @returns {$CancellablePromise<localapp$0.DiagnosticsExport>}
 */
export function ExportDiagnostics(input) {
    return $Call.ByID(2588330661, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<settings$0.Settings>}
 */
export function GetSettings() {
    return $Call.ByID(2008449894).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<localapp$0.StorageUsage>}
 */
export function GetStorageUsage() {
    return $Call.ByID(1990329599).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {localapp$0.CleanupPreviewInput} input
 * @returns {$CancellablePromise<localapp$0.CleanupPreview>}
 */
export function PreviewCleanup(input) {
    return $Call.ByID(840909829, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} section
 * @param {number} expectedRevision
 * @returns {$CancellablePromise<settings$0.Settings>}
 */
export function ResetSettingsSection(section, expectedRevision) {
    return $Call.ByID(986237464, section, expectedRevision).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function RevealDataRoot() {
    return $Call.ByID(2157276860);
}

/**
 * @param {settings$0.ExecutionSettings} input
 * @param {number} expectedRevision
 * @returns {$CancellablePromise<settings$0.Settings>}
 */
export function UpdateExecutionSettings(input, expectedRevision) {
    return $Call.ByID(1408201131, input, expectedRevision).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {settings$0.ExperimentalSettings} input
 * @param {number} expectedRevision
 * @returns {$CancellablePromise<settings$0.Settings>}
 */
export function UpdateExperimentalSettings(input, expectedRevision) {
    return $Call.ByID(2186188539, input, expectedRevision).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {{ [_ in string]?: settings$0.RuntimeSettings }} input
 * @param {number} expectedRevision
 * @returns {$CancellablePromise<settings$0.Settings>}
 */
export function UpdateRuntimeSettings(input, expectedRevision) {
    return $Call.ByID(1670399153, input, expectedRevision).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {settings$0.SecuritySettings} input
 * @param {number} expectedRevision
 * @returns {$CancellablePromise<settings$0.Settings>}
 */
export function UpdateSecuritySettings(input, expectedRevision) {
    return $Call.ByID(2697238491, input, expectedRevision).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {settings$0.StorageSettings} input
 * @param {number} expectedRevision
 * @returns {$CancellablePromise<settings$0.Settings>}
 */
export function UpdateStorageSettings(input, expectedRevision) {
    return $Call.ByID(905314724, input, expectedRevision).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

// Private type creation functions
const $$createType0 = localapp$0.RuntimeInfo.createFrom;
const $$createType1 = localapp$0.CleanupResult.createFrom;
const $$createType2 = localapp$0.DiagnosticsExport.createFrom;
const $$createType3 = settings$0.Settings.createFrom;
const $$createType4 = localapp$0.StorageUsage.createFrom;
const $$createType5 = localapp$0.CleanupPreview.createFrom;
