// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as localapp$0 from "../../../internal/app/localapp/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tasks$0 from "../../../internal/domain/tasks/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as workflows$0 from "../../../internal/domain/workflows/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as runstream$0 from "../../../internal/runstream/models.js";

/**
 * @param {string} runID
 * @returns {$CancellablePromise<workflows$0.Run>}
 */
export function CancelRun(runID) {
    return $Call.ByID(2676300487, runID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {localapp$0.CreateTaskInput} input
 * @returns {$CancellablePromise<tasks$0.Task>}
 */
export function CreateTask(input) {
    return $Call.ByID(1314009117, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} taskID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteTask(taskID) {
    return $Call.ByID(1400636366, taskID);
}

/**
 * @param {string} runID
 * @param {localapp$0.InstructionInput} input
 * @returns {$CancellablePromise<workflows$0.Instruction>}
 */
export function EnqueueInstruction(runID, input) {
    return $Call.ByID(1538789322, runID, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} taskID
 * @param {string} confirmationToken
 * @returns {$CancellablePromise<tasks$0.Task>}
 */
export function EnqueueTask(taskID, confirmationToken) {
    return $Call.ByID(2138368811, taskID, confirmationToken).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} runID
 * @returns {$CancellablePromise<localapp$0.RunDetail>}
 */
export function GetRun(runID) {
    return $Call.ByID(1098076141, runID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} runID
 * @returns {$CancellablePromise<runstream$0.Frame[]>}
 */
export function GetRunStreamSnapshot(runID) {
    return $Call.ByID(3157096981, runID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} runID
 * @param {localapp$0.InstructionInput} input
 * @returns {$CancellablePromise<workflows$0.Instruction>}
 */
export function InterruptAndInsert(runID, input) {
    return $Call.ByID(2407930173, runID, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} runID
 * @returns {$CancellablePromise<workflows$0.Run>}
 */
export function InterruptRun(runID) {
    return $Call.ByID(783360872, runID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} runID
 * @param {number} afterSeq
 * @returns {$CancellablePromise<localapp$0.WorkflowEventView[]>}
 */
export function ListRunEvents(runID, afterSeq) {
    return $Call.ByID(3352032840, runID, afterSeq).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {localapp$0.ListRunsInput} input
 * @returns {$CancellablePromise<localapp$0.RunListPage>}
 */
export function ListRuns(input) {
    return $Call.ByID(527758150, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @param {string} taskID
 * @returns {$CancellablePromise<workflows$0.Run[]>}
 */
export function ListRunsByTask(taskID) {
    return $Call.ByID(71078598, taskID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @param {string} workspaceID
 * @returns {$CancellablePromise<tasks$0.Task[]>}
 */
export function ListTasks(workspaceID) {
    return $Call.ByID(660765190, workspaceID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * @param {string} taskID
 * @returns {$CancellablePromise<localapp$0.RunStartPreview>}
 */
export function PreviewRun(taskID) {
    return $Call.ByID(2734983773, taskID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * @param {string} workspaceID
 * @returns {$CancellablePromise<tasks$0.Task[]>}
 */
export function QueueSnapshot(workspaceID) {
    return $Call.ByID(557416803, workspaceID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * @param {string} runID
 * @param {string} instructionID
 * @returns {$CancellablePromise<void>}
 */
export function RemoveInstruction(runID, instructionID) {
    return $Call.ByID(2230820116, runID, instructionID);
}

/**
 * @param {string} taskID
 * @param {string} title
 * @returns {$CancellablePromise<tasks$0.Task>}
 */
export function RenameTask(taskID, title) {
    return $Call.ByID(2119797299, taskID, title).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} runID
 * @param {string} instruction
 * @returns {$CancellablePromise<workflows$0.Run>}
 */
export function ResumeRun(runID, instruction) {
    return $Call.ByID(3819119624, runID, instruction).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} taskID
 * @param {string} confirmationToken
 * @returns {$CancellablePromise<workflows$0.Run>}
 */
export function StartRun(taskID, confirmationToken) {
    return $Call.ByID(2521904853, taskID, confirmationToken).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = workflows$0.Run.createFrom;
const $$createType1 = tasks$0.Task.createFrom;
const $$createType2 = workflows$0.Instruction.createFrom;
const $$createType3 = localapp$0.RunDetail.createFrom;
const $$createType4 = runstream$0.Frame.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = localapp$0.WorkflowEventView.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = localapp$0.RunListPage.createFrom;
const $$createType9 = $Create.Array($$createType0);
const $$createType10 = $Create.Array($$createType1);
const $$createType11 = localapp$0.RunStartPreview.createFrom;
