// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as localapp$0 from "../../../internal/app/localapp/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as workspaces$0 from "../../../internal/domain/workspaces/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as worker$0 from "../../../internal/worker/models.js";

/**
 * @param {string} id
 * @returns {$CancellablePromise<localapp$0.WorkerStatus>}
 */
export function CheckWorker(id) {
    return $Call.ByID(2059752536, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteWorker(id) {
    return $Call.ByID(474045851, id);
}

/**
 * @returns {$CancellablePromise<worker$0.Info[]>}
 */
export function ListWorkers() {
    return $Call.ByID(2045373053).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {worker$0.Input} input
 * @returns {$CancellablePromise<worker$0.Info>}
 */
export function SaveWorker(input) {
    return $Call.ByID(595776057, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} id
 * @param {string} workspaceID
 * @returns {$CancellablePromise<workspaces$0.GitSnapshot>}
 */
export function WorkerGitStatus(id, workspaceID) {
    return $Call.ByID(2243598250, id, workspaceID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

// Private type creation functions
const $$createType0 = localapp$0.WorkerStatus.createFrom;
const $$createType1 = worker$0.Info.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = workspaces$0.GitSnapshot.createFrom;
