// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as workflows$0 from "../../../internal/domain/workflows/models.js";

/**
 * @param {workflows$0.Definition} input
 * @returns {$CancellablePromise<workflows$0.Definition>}
 */
export function CreateDefinition(input) {
    return $Call.ByID(2677516260, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<workflows$0.Definition>}
 */
export function GetDefinition(id) {
    return $Call.ByID(423575518, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<workflows$0.Definition[]>}
 */
export function ListDefinitions() {
    return $Call.ByID(2126256753).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} id
 * @param {workflows$0.Definition} input
 * @returns {$CancellablePromise<workflows$0.Definition>}
 */
export function UpdateDefinition(id, input) {
    return $Call.ByID(2481601009, id, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {workflows$0.Definition} input
 * @returns {$CancellablePromise<workflows$0.ValidationIssue[]>}
 */
export function ValidateDefinition(input) {
    return $Call.ByID(1158537042, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

// Private type creation functions
const $$createType0 = workflows$0.Definition.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = workflows$0.ValidationIssue.createFrom;
const $$createType3 = $Create.Array($$createType2);
