import { useTranslation } from "react-i18next";
import { Action, TUISelect, Toolbar, ToolbarSpacer } from "../../../ui/primitives.jsx";
import { nextWorkflowItemID } from "../../workflowIds.js";
import { assignWorkflowWorker, isRemoteWorker } from "../../workflowWorker.js";
import DAGWorkflowEditor from "./DAGWorkflowEditor.jsx";
import WorkflowIdentityFields from "./WorkflowIdentityFields.jsx";

export default function WorkflowEditor({ editor, setEditor, validation, validateEditor, saveWorkflow, busy, updateStep, updateTransition, removeTransition, runtimes, workers, defaultSandbox, allowFullSandbox, onClose }) {
  const { t } = useTranslation();
  if (editor.mode === "dag") return <DAGWorkflowEditor editor={editor} setEditor={setEditor} validation={validation} validateEditor={validateEditor} saveWorkflow={saveWorkflow} busy={busy} runtimes={runtimes} workers={workers} defaultSandbox={defaultSandbox} allowFullSandbox={allowFullSandbox} onClose={onClose} />;
  const workerOptions = [{ value: "local", label: t("common.local") }, ...workers.filter((worker) => worker.enabled).map((worker) => ({ value: worker.id, label: worker.name }))];
  const updateWorker = (stepIndex, workerId) => setEditor((current) => ({ ...current, steps: current.steps.map((step, index) => index === stepIndex ? assignWorkflowWorker(step, workerId) : step) }));
  const addStep = () => setEditor((current) => {
    const id = nextWorkflowItemID("step", current.steps);
    return { ...current, steps: [...current.steps, { id, name: t("workflow.newStep"), runtime: "codex", model: "", workerId: "local", sandbox: defaultSandbox, rolePrompt: t("workflow.defaultRole"), instruction: t("workflow.defaultInstruction"), transitions: { completed: "$done" } }] };
  });
  const removeStep = (index) => setEditor((current) => ({ ...current, steps: current.steps.filter((_, itemIndex) => itemIndex !== index) }));
  return <section className="workflow-editor-surface">
    <Toolbar className="editor-toolbar"><Action onClick={onClose}>&lt; {t("common.back")}</Action><WorkflowIdentityFields editor={editor} setEditor={setEditor} validation={validation} /><ToolbarSpacer /><Action tone="cyan" onClick={validateEditor}>{t("workflow.validate")}</Action><Action tone="primary" disabled={busy === "workflow"} onClick={saveWorkflow}>{busy === "workflow" ? t("common.saving") : t("common.save")}</Action></Toolbar>
    <div className="editor-layout"><div className="editor-main"><div className="step-editor-list">{editor.steps.map((step, stepIndex) => <section className="step-editor" key={`${step.id}-${stepIndex}`}>
      <div className="step-editor-head"><b>{String(stepIndex + 1).padStart(2, "0")}</b><input aria-label={t("workflow.stepName")} value={step.name} onChange={(event) => updateStep(stepIndex, "name", event.target.value)} /><TUISelect ariaLabel={t("common.runtime")} value={step.runtime} onChange={(runtime) => updateStep(stepIndex, "runtime", runtime)} options={runtimes.map((runtime) => ({ value: runtime.id, label: runtime.id, meta: runtime.available ? "" : t("common.missing") }))} /><TUISelect ariaLabel={t("common.worker")} value={step.workerId || "local"} onChange={(workerId) => updateWorker(stepIndex, workerId)} options={workerOptions} /><TUISelect ariaLabel={t("common.sandbox")} value={step.sandbox || "workspace-write"} onChange={(sandbox) => updateStep(stepIndex, "sandbox", sandbox)} options={[{ value: "read-only", label: t("workspace.readOnly") }, { value: "workspace-write", label: t("workspace.write"), disabled: isRemoteWorker(step.workerId) }, { value: "full", label: t("workspace.fullDanger"), disabled: isRemoteWorker(step.workerId) || (!allowFullSandbox && step.sandbox !== "full") }]} /><Action size="compact" tone="danger" disabled={editor.steps.length <= 1} onClick={() => removeStep(stepIndex)}>{t("workflow.deleteStep")}</Action></div>
      <div className="step-editor-grid"><label>{t("workflow.rolePrompt")}<textarea value={step.rolePrompt} onChange={(event) => updateStep(stepIndex, "rolePrompt", event.target.value)} /></label><label>{t("workflow.stepInstruction")}<textarea value={step.instruction} onChange={(event) => updateStep(stepIndex, "instruction", event.target.value)} /></label></div>
      <div className="transition-editor"><span>{t("workflow.transitions")}</span>{Object.entries(step.transitions || {}).map(([signal, target]) => <div className="transition-row" key={signal}><input value={signal} onChange={(event) => updateTransition(stepIndex, signal, event.target.value, target)} /><span>→</span><input value={target} onChange={(event) => updateTransition(stepIndex, signal, signal, event.target.value)} /><Action size="compact" tone="danger" onClick={() => removeTransition(stepIndex, signal)}>{t("common.delete")}</Action></div>)}<Action size="compact" onClick={() => updateTransition(stepIndex, `signal_${Object.keys(step.transitions || {}).length + 1}`, `signal_${Object.keys(step.transitions || {}).length + 1}`, "$done")}>+ {t("workflow.addSignal")}</Action></div>
    </section>)}</div><Action className="add-step" onClick={addStep}>+ {t("workflow.addStep")}</Action></div>
    <aside className="editor-side"><span className="kicker">{t("workflow.preview")}</span><pre className="flow-ascii">{editor.steps.map((step, index) => `${index ? "│\n" : ""}┌─ ${index + 1} ${step.name}      ${step.runtime}\n${Object.entries(step.transitions || {}).map(([signal, target]) => `│  ${signal} → ${target}`).join("\n")}`).join("\n")}</pre><div className="policy-box"><span>{t("workflow.policy")}</span><p>{t("workflow.maxTransitions")} <b>{editor.policy?.maxTransitions || 20}</b></p><p>{t("workflow.maxFailures")} <b>{editor.policy?.maxConsecutiveFailures || 3}</b></p><p>{t("workflow.stepTimeout")} <b>{editor.policy?.stepTimeoutSeconds || 1800}s</b></p></div><div className={`validation-box ${validation.length ? "has-errors" : "valid"}`}><div><strong>{t("workflow.validation")}</strong><b>{validation.length ? t("workflow.errorsCount", { count: validation.length }) : t("workflow.ok")}</b></div>{validation.map((issue, index) => <p key={`${issue.path}-${index}`}><code>{issue.path}</code>{issue.message}</p>)}{!validation.length && <p>{t("workflow.validationHint")}</p>}</div></aside></div>
  </section>;
}
