// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/openmodu/oneshot/clients/oneshot"
)

// Injectors from wire.go:

func initializeClient() oneshot.Client {
	string2 := apiBaseURL()
	httpClient := oneshot.NewHTTPClient(string2)
	return httpClient
}
