// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NotifyBinding sends a macOS system notification for a standby edge (all tasks
 * finished, or a run now needs the user). It is deliberately best-effort: the
 * notifier is nil unless the app runs from a signed .app bundle, in which case
 * Send is a no-op. The frontend already reflects the same change on the standby
 * screen, so a missing notification is never a functional loss.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Send delivers one notification. Authorization is requested lazily on the first
 * call so the OS prompt only appears once the feature is actually used.
 * @param {string} title
 * @param {string} body
 * @returns {$CancellablePromise<void>}
 */
export function Send(title, body) {
    return $Call.ByID(3289703892, title, body);
}
