// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agentrun$0 from "../../agentrun/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as localapp$0 from "../../app/localapp/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../../domain/settings/models.js";

/**
 * @param {localapp$0.RuntimeDraftInput} input
 * @returns {$CancellablePromise<localapp$0.RuntimeInfo>}
 */
export function CheckRuntimeDraft(input) {
    return $Call.ByID(1435668421, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} previewToken
 * @returns {$CancellablePromise<localapp$0.CleanupResult>}
 */
export function ExecuteCleanup(previewToken) {
    return $Call.ByID(107405019, previewToken).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {localapp$0.DiagnosticsExportInput} input
 * @returns {$CancellablePromise<localapp$0.DiagnosticsExport>}
 */
export function ExportDiagnostics(input) {
    return $Call.ByID(4267042136, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<settings$0.Settings>}
 */
export function GetSettings() {
    return $Call.ByID(132823455).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<localapp$0.StorageUsage>}
 */
export function GetStorageUsage() {
    return $Call.ByID(1781994734).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {settings$0.RuntimeSettings} input
 * @returns {$CancellablePromise<agentrun$0.ClaudeConfiguration>}
 */
export function InspectClaudeConfiguration(input) {
    return $Call.ByID(2980690882, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {settings$0.RuntimeSettings} input
 * @returns {$CancellablePromise<agentrun$0.CodexConfiguration>}
 */
export function InspectCodexConfiguration(input) {
    return $Call.ByID(2574097689, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {localapp$0.CleanupPreviewInput} input
 * @returns {$CancellablePromise<localapp$0.CleanupPreview>}
 */
export function PreviewCleanup(input) {
    return $Call.ByID(204616186, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {string} section
 * @param {number} expectedRevision
 * @returns {$CancellablePromise<settings$0.Settings>}
 */
export function ResetSettingsSection(section, expectedRevision) {
    return $Call.ByID(2482006795, section, expectedRevision).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function RevealDataRoot() {
    return $Call.ByID(1995342103);
}

/**
 * @param {settings$0.ExecutionSettings} input
 * @param {number} expectedRevision
 * @returns {$CancellablePromise<settings$0.Settings>}
 */
export function UpdateExecutionSettings(input, expectedRevision) {
    return $Call.ByID(3071566258, input, expectedRevision).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {settings$0.ExperimentalSettings} input
 * @param {number} expectedRevision
 * @returns {$CancellablePromise<settings$0.Settings>}
 */
export function UpdateExperimentalSettings(input, expectedRevision) {
    return $Call.ByID(2850770516, input, expectedRevision).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {{ [_ in string]?: settings$0.RuntimeSettings }} input
 * @param {number} expectedRevision
 * @returns {$CancellablePromise<settings$0.Settings>}
 */
export function UpdateRuntimeSettings(input, expectedRevision) {
    return $Call.ByID(1574166580, input, expectedRevision).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {settings$0.SecuritySettings} input
 * @param {number} expectedRevision
 * @returns {$CancellablePromise<settings$0.Settings>}
 */
export function UpdateSecuritySettings(input, expectedRevision) {
    return $Call.ByID(685027180, input, expectedRevision).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {settings$0.StorageSettings} input
 * @param {number} expectedRevision
 * @returns {$CancellablePromise<settings$0.Settings>}
 */
export function UpdateStorageSettings(input, expectedRevision) {
    return $Call.ByID(1112335761, input, expectedRevision).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

// Private type creation functions
const $$createType0 = localapp$0.RuntimeInfo.createFrom;
const $$createType1 = localapp$0.CleanupResult.createFrom;
const $$createType2 = localapp$0.DiagnosticsExport.createFrom;
const $$createType3 = settings$0.Settings.createFrom;
const $$createType4 = localapp$0.StorageUsage.createFrom;
const $$createType5 = agentrun$0.ClaudeConfiguration.createFrom;
const $$createType6 = agentrun$0.CodexConfiguration.createFrom;
const $$createType7 = localapp$0.CleanupPreview.createFrom;
