// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as workflows$0 from "../../domain/workflows/models.js";

/**
 * @param {workflows$0.Definition} input
 * @returns {$CancellablePromise<workflows$0.Definition>}
 */
export function CreateDefinition(input) {
    return $Call.ByID(3657752119, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteDefinition(id) {
    return $Call.ByID(1756534544, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<workflows$0.Definition>}
 */
export function GetDefinition(id) {
    return $Call.ByID(2556417119, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<workflows$0.Definition[]>}
 */
export function ListDefinitions() {
    return $Call.ByID(1500561572).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} id
 * @param {workflows$0.Definition} input
 * @returns {$CancellablePromise<workflows$0.Definition>}
 */
export function UpdateDefinition(id, input) {
    return $Call.ByID(1323010878, id, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {workflows$0.Definition} input
 * @returns {$CancellablePromise<workflows$0.ValidationIssue[]>}
 */
export function ValidateDefinition(input) {
    return $Call.ByID(1326098125, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

// Private type creation functions
const $$createType0 = workflows$0.Definition.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = workflows$0.ValidationIssue.createFrom;
const $$createType3 = $Create.Array($$createType2);
