// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Health {
    /**
     * Creates a new Health instance.
     * @param {Partial<Health>} [$$source = {}] - The source object to create the Health.
     */
    constructor($$source = {}) {
        if (!("workerId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["workerId"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("runtimes" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: boolean }}
             */
            this["runtimes"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Health instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Health}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("runtimes" in $$parsedSource) {
            $$parsedSource["runtimes"] = $$createField2_0($$parsedSource["runtimes"]);
        }
        return new Health(/** @type {Partial<Health>} */($$parsedSource));
    }
}

export class Info {
    /**
     * Creates a new Info instance.
     * @param {Partial<Info>} [$$source = {}] - The source object to create the Info.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("baseUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["baseUrl"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("hasToken" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasToken"] = false;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updatedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Info instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Info}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Info(/** @type {Partial<Info>} */($$parsedSource));
    }
}

export class Input {
    /**
     * Creates a new Input instance.
     * @param {Partial<Input>} [$$source = {}] - The source object to create the Input.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("baseUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["baseUrl"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["token"] = undefined;
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Input instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Input}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Input(/** @type {Partial<Input>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
